In [15]:
# imports

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')


%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn'

In [16]:
pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [17]:
ls -lh ./data

total 1.4M
-rw-r--r-- 1 dgaillot dgaillot 1.2M Feb  1 09:47 2016_Building_Energy_Benchmarking.csv
-rw-r--r-- 1 dgaillot dgaillot 136K Feb  8 15:39 clean_seattle_buildings.csv

In [18]:
path = './data/'
filename = 'clean_seattle_buildings.csv'
csv_path = path + filename
df = pd.read_csv(csv_path, on_bad_lines='skip', low_memory=False)

In [19]:
df.head()

,BuildingType,PrimaryPropertyType,ZipCode,Neighborhood,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType,ENERGYSTARScore,SiteEnergyUseWN(kBtu),TotalGHGEmissions
0,NonResidential,Hotel,98101.0,DOWNTOWN,1927,1.0,12,88434,0,88434,Hotel,No UseType,No UseType,60.0,7456910.0,249.98
1,NonResidential,Hotel,98101.0,DOWNTOWN,1996,1.0,11,103566,15064,88502,Hotel,Parking,Restaurant,61.0,8664479.0,295.86
2,NonResidential,Hotel,98101.0,DOWNTOWN,1969,1.0,41,956110,196718,759392,Hotel,No UseType,No UseType,43.0,73937112.0,2089.28
3,NonResidential,Hotel,98101.0,DOWNTOWN,1926,1.0,10,61320,0,61320,Hotel,No UseType,No UseType,56.0,6946800.5,286.43
4,NonResidential,Hotel,98121.0,DOWNTOWN,1980,1.0,18,175580,62000,113580,Hotel,Parking,Swimming Pool,75.0,14656503.0,505.01

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1023 entries, 0 to 1022
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BuildingType                  1023 non-null   object
 1   PrimaryPropertyType           1023 non-null   object
 2   ZipCode                       1023 non-null   float64
 3   Neighborhood                  1023 non-null   object
 4   YearBuilt                     1023 non-null   int64
 5   NumberofBuildings             1023 non-null   float64
 6   NumberofFloors                1023 non-null   int64
 7   PropertyGFATotal              1023 non-null   int64
 8   PropertyGFAParking            1023 non-null   int64
 9   PropertyGFABuilding(s)        1023 non-null   int64
 10  LargestPropertyUseType        1023 non-null   object
 11  SecondLargestPropertyUseType  1023 non-null   object
 12  ThirdLargestPropertyUseType   1023 non-null   object
 13  ENERGYSTARScore               1023 non-null   float64
 14  SiteEnergyUseWN(kBtu)         1023 non-null   float64
 15  TotalGHGEmissions             1023 non-null   float64
dtypes: float64(5), int64(5), object(6)
memory usage: 128.0+ KB

In [21]:
df.dtypes

BuildingType                     object
PrimaryPropertyType              object
ZipCode                         float64
Neighborhood                     object
YearBuilt                         int64
NumberofBuildings               float64
NumberofFloors                    int64
PropertyGFATotal                  int64
PropertyGFAParking                int64
PropertyGFABuilding(s)            int64
LargestPropertyUseType           object
SecondLargestPropertyUseType     object
ThirdLargestPropertyUseType      object
ENERGYSTARScore                 float64
SiteEnergyUseWN(kBtu)           float64
TotalGHGEmissions               float64
dtype: object

In [22]:
df.shape

(1023, 16)

In [23]:
df.isna().sum().sum()

0

In [24]:
#save separately energy star score
energy_star_score = df['ENERGYSTARScore']
df.drop('ENERGYSTARScore', axis=1, inplace=True)
df.shape

(1023, 15)

In [25]:
#df.isna().sum().sum()

# Prep Vectors & Matrices

In [26]:
y = df.copy()[{'SiteEnergyUseWN(kBtu)', 'TotalGHGEmissions'}]
X = df.copy().drop(['SiteEnergyUseWN(kBtu)', 'TotalGHGEmissions'], axis=1)

## Normalisation & One Hot Encoder

In [27]:
X.select_dtypes(['category','object']).nunique()

BuildingType                     4
PrimaryPropertyType             14
Neighborhood                    13
LargestPropertyUseType          19
SecondLargestPropertyUseType    31
ThirdLargestPropertyUseType     29
dtype: int64

In [28]:
X.shape

(1023, 13)

In [29]:
### isoler var num et var cat
categorical_columns = X.select_dtypes(['category','object']).columns
numerical_columns = X.select_dtypes(['int32','float64']).columns

In [30]:
categorical_columns

Index(['BuildingType', 'PrimaryPropertyType', 'Neighborhood',
       'LargestPropertyUseType', 'SecondLargestPropertyUseType',
       'ThirdLargestPropertyUseType'],
      dtype='object')

In [31]:
numerical_columns

Index(['ZipCode', 'NumberofBuildings'], dtype='object')

In [32]:
df.describe()

,ZipCode,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),SiteEnergyUseWN(kBtu),TotalGHGEmissions
count,1023.000000,1023.000000,1023.000000,1023.00000,1.023000e+03,1023.000000,1.023000e+03,1.023000e+03,1023.000000
mean,98116.467253,1963.283480,1.044966,4.85826,1.245587e+05,15167.322581,1.093914e+05,8.629258e+06,184.392688
std,17.512608,31.601602,0.482504,7.94923,2.033426e+05,46280.616303,1.769342e+05,2.601223e+07,848.363277
min,98020.000000,1900.000000,1.000000,0.00000,1.630000e+04,0.000000,1.620000e+04,7.996790e+04,-0.800000
25%,98104.000000,1938.000000,1.000000,1.00000,3.254550e+04,0.000000,3.132150e+04,1.396912e+06,20.560000
50%,98109.000000,1967.000000,1.000000,3.00000,5.373000e+04,0.000000,5.105000e+04,2.789344e+06,49.250000
75%,98122.000000,1989.000000,1.000000,5.00000,1.229710e+05,0.000000,1.060205e+05,7.424380e+06,130.655000
max,98199.000000,2015.000000,9.000000,99.00000,1.952220e+06,512608.000000,1.765970e+06,4.716139e+08,16870.980000

In [33]:
df[categorical_columns].describe()

,BuildingType,PrimaryPropertyType,Neighborhood,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType
count,1023,1023,1023,1023,1023,1023
unique,4,14,13,19,31,29
top,NonResidential,Small- and Mid-Sized Office,DOWNTOWN,Office,No UseType,No UseType
freq,929,235,236,396,555,880

In [34]:
df[categorical_columns].dtypes

BuildingType                    object
PrimaryPropertyType             object
Neighborhood                    object
LargestPropertyUseType          object
SecondLargestPropertyUseType    object
ThirdLargestPropertyUseType     object
dtype: object

In [35]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

ohe = OneHotEncoder(sparse=False)
ss = StandardScaler()

In [36]:
### normaliser num
X[numerical_columns] = ss.fit_transform(X[numerical_columns])

In [37]:
### transformer var cat (OHE ou ordinal)
## bcp valeurs diff =>  favoriser ordinal encoding (enlever les 2 cols de target)
df[categorical_columns].nunique()

BuildingType                     4
PrimaryPropertyType             14
Neighborhood                    13
LargestPropertyUseType          19
SecondLargestPropertyUseType    31
ThirdLargestPropertyUseType     29
dtype: int64

In [38]:
df['LargestPropertyUseType'].unique()

array(['Hotel', 'Courthouse', 'K-12 School', 'Office', 'Medical Office',
       'Retail Store', 'Hospital (General Medical & Surgical)',
       'Financial Office', 'Non-Refrigerated Warehouse',
       'Worship Facility', 'Data Center', 'Parking',
       'Supermarket/Grocery Store', 'Distribution Center',
       'Wholesale Club/Supercenter', 'Refrigerated Warehouse', 'Other',
       'No UseType', 'Bank Branch'], dtype=object)

In [39]:
# => réencoder manuellement en classes générales

In [40]:
ohe.fit_transform(X[categorical_columns])

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [41]:
X[categorical_columns].head()

,BuildingType,PrimaryPropertyType,Neighborhood,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType
0,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
1,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Restaurant
2,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
3,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
4,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Swimming Pool

In [42]:
X[categorical_columns].head()

,BuildingType,PrimaryPropertyType,Neighborhood,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType
0,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
1,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Restaurant
2,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
3,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType
4,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Swimming Pool

In [44]:
X = pd.merge(X[categorical_columns], 
          pd.DataFrame(columns = ohe.get_feature_names().tolist(),
              data = ohe.fit_transform(X[categorical_columns])),
        left_index = True, right_index = True)

In [45]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1023 entries, 0 to 1022
Columns: 116 entries, BuildingType to x5_Swimming Pool
dtypes: float64(110), object(6)
memory usage: 927.2+ KB

In [46]:
X.head()

,BuildingType,PrimaryPropertyType,Neighborhood,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType,x0_Campus,x0_NonResidential,x0_Nonresidential COS,x0_SPS-District K-12,x1_Distribution Center,x1_Hospital,x1_Hotel,x1_K-12 School,x1_Large Office,x1_Medical Office,x1_Mixed Use Property,x1_Other,x1_Refrigerated Warehouse,x1_Retail Store,x1_Small- and Mid-Sized Office,x1_Supermarket / Grocery Store,x1_Warehouse,x1_Worship Facility,x2_BALLARD,x2_CENTRAL,x2_DELRIDGE,x2_DOWNTOWN,x2_EAST,x2_GREATER DUWAMISH,x2_LAKE UNION,x2_MAGNOLIA / QUEEN ANNE,x2_NORTH,x2_NORTHEAST,x2_NORTHWEST,x2_SOUTHEAST,x2_SOUTHWEST,x3_Bank Branch,x3_Courthouse,x3_Data Center,x3_Distribution Center,x3_Financial Office,x3_Hospital (General Medical & Surgical),x3_Hotel,x3_K-12 School,x3_Medical Office,x3_No UseType,x3_Non-Refrigerated Warehouse,x3_Office,x3_Other,x3_Parking,x3_Refrigerated Warehouse,x3_Retail Store,x3_Supermarket/Grocery Store,x3_Wholesale Club/Supercenter,x3_Worship Facility,x4_Adult Education,x4_Bank Branch,x4_Bar/Nightclub,x4_College/University,x4_Convenience Store without Gas Station,x4_Data Center,x4_Distribution Center,x4_Financial Office,x4_Hotel,x4_K-12 School,x4_Laboratory,x4_Manufacturing/Industrial Plant,x4_Medical Office,x4_No UseType,x4_Non-Refrigerated Warehouse,x4_Office,x4_Other,x4_Other - Education,x4_Other - Entertainment/Public Assembly,x4_Other - Recreation,x4_Other - Restaurant/Bar,x4_Other - Services,x4_Parking,x4_Performing Arts,x4_Pre-school/Daycare,x4_Restaurant,x4_Retail Store,x4_Self-Storage Facility,x4_Supermarket/Grocery Store,x4_Swimming Pool,x4_Worship Facility,x5_Bank Branch,x5_Bar/Nightclub,x5_Convenience Store without Gas Station,x5_Data Center,x5_Distribution Center,x5_Financial Office,x5_Fitness Center/Health Club/Gym,x5_Food Service,x5_Laboratory,x5_Medical Office,x5_No UseType,x5_Non-Refrigerated Warehouse,x5_Office,x5_Other,x5_Other - Education,x5_Other - Entertainment/Public Assembly,x5_Other - Recreation,x5_Other - Restaurant/Bar,x5_Other - Services,x5_Other - Technology/Science,x5_Other/Specialty Hospital,x5_Parking,"x5_Personal Services (Health/Beauty, Dry Cleaning, etc)",x5_Pre-school/Daycare,x5_Refrigerated Warehouse,x5_Restaurant,x5_Retail Store,x5_Social/Meeting Hall,x5_Swimming Pool
0,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Restaurant,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,NonResidential,Hotel,DOWNTOWN,Hotel,No UseType,No UseType,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NonResidential,Hotel,DOWNTOWN,Hotel,Parking,Swimming Pool,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [47]:
#import re
#regex = re.compile(r'x\d_')
#for column in X.columns:
#    if regex.search(column):
#        X[column] = X[column].astype('int32')

In [62]:
categorical_columns

Index(['BuildingType', 'PrimaryPropertyType', 'Neighborhood',
       'LargestPropertyUseType', 'SecondLargestPropertyUseType',
       'ThirdLargestPropertyUseType'],
      dtype='object')

In [64]:
X.drop(columns=categorical_columns, inplace = True)
X.head()

,x0_Campus,x0_NonResidential,x0_Nonresidential COS,x0_SPS-District K-12,x1_Distribution Center,x1_Hospital,x1_Hotel,x1_K-12 School,x1_Large Office,x1_Medical Office,x1_Mixed Use Property,x1_Other,x1_Refrigerated Warehouse,x1_Retail Store,x1_Small- and Mid-Sized Office,x1_Supermarket / Grocery Store,x1_Warehouse,x1_Worship Facility,x2_BALLARD,x2_CENTRAL,x2_DELRIDGE,x2_DOWNTOWN,x2_EAST,x2_GREATER DUWAMISH,x2_LAKE UNION,x2_MAGNOLIA / QUEEN ANNE,x2_NORTH,x2_NORTHEAST,x2_NORTHWEST,x2_SOUTHEAST,x2_SOUTHWEST,x3_Bank Branch,x3_Courthouse,x3_Data Center,x3_Distribution Center,x3_Financial Office,x3_Hospital (General Medical & Surgical),x3_Hotel,x3_K-12 School,x3_Medical Office,x3_No UseType,x3_Non-Refrigerated Warehouse,x3_Office,x3_Other,x3_Parking,x3_Refrigerated Warehouse,x3_Retail Store,x3_Supermarket/Grocery Store,x3_Wholesale Club/Supercenter,x3_Worship Facility,x4_Adult Education,x4_Bank Branch,x4_Bar/Nightclub,x4_College/University,x4_Convenience Store without Gas Station,x4_Data Center,x4_Distribution Center,x4_Financial Office,x4_Hotel,x4_K-12 School,x4_Laboratory,x4_Manufacturing/Industrial Plant,x4_Medical Office,x4_No UseType,x4_Non-Refrigerated Warehouse,x4_Office,x4_Other,x4_Other - Education,x4_Other - Entertainment/Public Assembly,x4_Other - Recreation,x4_Other - Restaurant/Bar,x4_Other - Services,x4_Parking,x4_Performing Arts,x4_Pre-school/Daycare,x4_Restaurant,x4_Retail Store,x4_Self-Storage Facility,x4_Supermarket/Grocery Store,x4_Swimming Pool,x4_Worship Facility,x5_Bank Branch,x5_Bar/Nightclub,x5_Convenience Store without Gas Station,x5_Data Center,x5_Distribution Center,x5_Financial Office,x5_Fitness Center/Health Club/Gym,x5_Food Service,x5_Laboratory,x5_Medical Office,x5_No UseType,x5_Non-Refrigerated Warehouse,x5_Office,x5_Other,x5_Other - Education,x5_Other - Entertainment/Public Assembly,x5_Other - Recreation,x5_Other - Restaurant/Bar,x5_Other - Services,x5_Other - Technology/Science,x5_Other/Specialty Hospital,x5_Parking,"x5_Personal Services (Health/Beauty, Dry Cleaning, etc)",x5_Pre-school/Daycare,x5_Refrigerated Warehouse,x5_Restaurant,x5_Retail Store,x5_Social/Meeting Hall,x5_Swimming Pool
0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [65]:
X.shape

(1023, 110)

In [66]:
y.shape

(1023, 2)

In [67]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
            train_test_split(X, 
                             y['SiteEnergyUseWN(kBtu)'],  
                             test_size = 0.2, 
                             random_state = 42
                            )

In [68]:
X_train.shape

(818, 110)

In [69]:
X_test.shape

(205, 110)

In [70]:
y_train.shape

(818,)

In [71]:
y_test.shape

(205,)

# Modélisation

In [72]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error

In [ ]:
from sklearn.linear_model import ElasticNet

#rappel de la fonction de coût du elasticnet
#1 / (2 * n_samples) * ||y - Xw||^2_2 + alpha * l1_ratio * ||w||_1 + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2

parameters = {'tol' : [0.1,0.01,0.001,0.0001],
              "alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],  #alpha, coef qui multiplie le terme de pénalité)
              "l1_ratio": np.arange(0.0, 1.0, 0.1)}#L1 ratio , =1 équivaut à un Lasso, 0 à un Ridge


elastic_grid = GridSearchCV(estimator = ElasticNet(), 
                      param_grid = parameters,
                      scoring = 'neg_mean_squared_error',
                      cv=5,
                      verbose=0
                     )

elastic_grid.fit(X_train, y_train)

In [ ]:
elastic_grid.best_params_

In [199]:
# 3 preds différentes (regression...mini une linéaire et une non-linéaire ex: linear regressor, random forest)
# optimisation hyper paramètres

## comparer avec même score (RMSE, R² (surtout pour linéaires))
## logger + comparer temps de test/entraînement
## ressortir tableau comparatif
## choisir meilleur

## une fois modele choisi, ajouter energystarscore
## evaluer si cela améliore ou non la modélisation
## utiliser librairie pour évaluer => librairie SHAP

In [ ]:
## possibilité de lister différents scorings à calculer en une fois => doc

In [ ]:
## essayer assembliste / random forest / svr / linearregression 
## check doc scikitlab regresseurs
## /!\ ne pas oublier normalisation

In [ ]:
## /!\ 2 targets => virer les 2 => 2 colonnes de moins pour l'ordinal encoding puis ajouter une target à la fois par training

In [ ]:
# analyse
# nettoyage (outliers + valeurs vides)
# (penser à encoder null en une autre valeur si besoin, par ex pour l'encoding, puis signifier à l'inputer que telle valeur est nulle)
# encoding
# encode > cat > -5 : OHE
#                +5 : ordinal
#         > cat >