In [1]:
# imports

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')


%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [3]:
ls -lh ./data

total 1,5M
-rw-r--r-- 1 mijka mijka 1,2M 23 sept. 16:03 2016_Building_Energy_Benchmarking.csv
-rw-r--r-- 1 mijka mijka 322K 24 janv. 15:49 clean_seattle_buildings.csv

In [4]:
path = './data/'
filename = 'clean_seattle_buildings.csv'
csv_path = path + filename
df = pd.read_csv(csv_path, on_bad_lines='skip', low_memory=False)

In [5]:
df.head()

,DataYear,BuildingType,PrimaryPropertyType,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),LargestPropertyUseType,LargestPropertyUseTypeGFA,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,ENERGYSTARScore,SiteEnergyUseWN(kBtu),DefaultData,ComplianceStatus,TotalGHGEmissions,geometry
0,2016,NonResidential,Hotel,7,DOWNTOWN,47.61220,-122.33799,1927,1.0,12,88434,0,88434,Hotel,88434.0,NaN,NaN,NaN,NaN,60.0,7456910.0,False,Compliant,249.98,POINT (-122.33799 47.6122)
1,2016,NonResidential,Hotel,7,DOWNTOWN,47.61317,-122.33393,1996,1.0,11,103566,15064,88502,Hotel,83880.0,Parking,15064.0,Restaurant,4622.0,61.0,8664479.0,False,Compliant,295.86,POINT (-122.33393 47.61317)
2,2016,NonResidential,Hotel,7,DOWNTOWN,47.61393,-122.33810,1969,1.0,41,956110,196718,759392,Hotel,756493.0,NaN,NaN,NaN,NaN,43.0,73937112.0,False,Compliant,2089.28,POINT (-122.3381 47.61393)
3,2016,NonResidential,Hotel,7,DOWNTOWN,47.61412,-122.33664,1926,1.0,10,61320,0,61320,Hotel,61320.0,NaN,NaN,NaN,NaN,56.0,6946800.5,False,Compliant,286.43,POINT (-122.33664 47.61412)
4,2016,NonResidential,Hotel,7,DOWNTOWN,47.61375,-122.34047,1980,1.0,18,175580,62000,113580,Hotel,123445.0,Parking,68009.0,Swimming Pool,0.0,75.0,14656503.0,False,Compliant,505.01,POINT (-122.34047 47.61375)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   DataYear                         1645 non-null   int64
 1   BuildingType                     1645 non-null   object
 2   PrimaryPropertyType              1645 non-null   object
 3   CouncilDistrictCode              1645 non-null   int64
 4   Neighborhood                     1645 non-null   object
 5   Latitude                         1645 non-null   float64
 6   Longitude                        1645 non-null   float64
 7   YearBuilt                        1645 non-null   int64
 8   NumberofBuildings                1643 non-null   float64
 9   NumberofFloors                   1645 non-null   int64
 10  PropertyGFATotal                 1645 non-null   int64
 11  PropertyGFAParking               1645 non-null   int64
 12  PropertyGFABuilding(s)           1645 non-null   int64
 13  LargestPropertyUseType           1639 non-null   object
 14  LargestPropertyUseTypeGFA        1639 non-null   float64
 15  SecondLargestPropertyUseType     846 non-null    object
 16  SecondLargestPropertyUseTypeGFA  846 non-null    float64
 17  ThirdLargestPropertyUseType      350 non-null    object
 18  ThirdLargestPropertyUseTypeGFA   350 non-null    float64
 19  SiteEnergyUseWN(kBtu)            1642 non-null   float64
 20  DefaultData                      1645 non-null   bool
 21  ComplianceStatus                 1645 non-null   object
 22  TotalGHGEmissions                1643 non-null   float64
 23  geometry                         1645 non-null   object
dtypes: bool(1), float64(8), int64(7), object(8)
memory usage: 297.3+ KB

In [6]:
df.dtypes

DataYear                             int64
BuildingType                        object
PrimaryPropertyType                 object
CouncilDistrictCode                  int64
Neighborhood                        object
Latitude                           float64
Longitude                          float64
YearBuilt                            int64
NumberofBuildings                  float64
NumberofFloors                       int64
PropertyGFATotal                     int64
PropertyGFAParking                   int64
PropertyGFABuilding(s)               int64
LargestPropertyUseType              object
LargestPropertyUseTypeGFA          float64
SecondLargestPropertyUseType        object
SecondLargestPropertyUseTypeGFA    float64
ThirdLargestPropertyUseType         object
ThirdLargestPropertyUseTypeGFA     float64
ENERGYSTARScore                    float64
SiteEnergyUseWN(kBtu)              float64
DefaultData                           bool
ComplianceStatus                    object
TotalGHGEmissions                  float64
geometry                            object
dtype: object

In [7]:
df.shape

(1645, 25)

In [29]:
df.isna().sum().sum()

4207

In [9]:
#save separately energy star score
energy_star_score = df['ENERGYSTARScore']
df.drop('ENERGYSTARScore', axis=1, inplace=True)

In [10]:
df.shape

(1645, 24)

In [11]:
#df.isna().sum().sum()

# Prep Vectors & Matrices

In [12]:
y = df.copy()[{'SiteEnergyUseWN(kBtu)', 'TotalGHGEmissions'}]
X = df.copy().drop(['SiteEnergyUseWN(kBtu)', 'TotalGHGEmissions'], axis=1)

## Normalisation & One Hot Encoder

In [13]:
X.select_dtypes(['category','object']).nunique()

BuildingType                       5
PrimaryPropertyType               22
Neighborhood                      13
LargestPropertyUseType            55
SecondLargestPropertyUseType      47
ThirdLargestPropertyUseType       39
ComplianceStatus                   4
geometry                        1577
dtype: int64

In [14]:
X.shape

(1645, 22)

In [15]:
categorical_columns = X.select_dtypes(['category','object']).columns
numerical_columns = X.select_dtypes(['int32','float64']).columns

In [16]:
categorical_columns

Index(['BuildingType', 'PrimaryPropertyType', 'Neighborhood',
       'LargestPropertyUseType', 'SecondLargestPropertyUseType',
       'ThirdLargestPropertyUseType', 'ComplianceStatus', 'geometry'],
      dtype='object')

In [17]:
numerical_columns

Index(['Latitude', 'Longitude', 'NumberofBuildings',
       'LargestPropertyUseTypeGFA', 'SecondLargestPropertyUseTypeGFA',
       'ThirdLargestPropertyUseTypeGFA'],
      dtype='object')

In [18]:
df.describe()

,DataYear,CouncilDistrictCode,Latitude,Longitude,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),LargestPropertyUseTypeGFA,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseTypeGFA,SiteEnergyUseWN(kBtu),TotalGHGEmissions
count,1645.0,1645.000000,1645.000000,1645.000000,1645.000000,1643.000000,1645.000000,1.645000e+03,1645.000000,1.645000e+03,1.639000e+03,846.000000,350.000000,1.642000e+03,1643.000000
mean,2016.0,4.355623,47.616010,-122.332932,1962.080243,1.168594,4.143465,1.188775e+05,13036.722796,1.058408e+05,9.882901e+04,36239.091367,14950.258282,8.119547e+06,187.181150
std,0.0,2.191967,0.048149,0.024600,32.642700,2.950288,6.603294,2.976366e+05,42536.529582,2.843112e+05,2.775072e+05,66507.866422,36936.960871,2.215524e+07,756.930034
min,2016.0,1.000000,47.499170,-122.411820,1900.000000,0.000000,0.000000,1.128500e+04,0.000000,3.636000e+03,5.656000e+03,0.000000,0.000000,0.000000e+00,-0.800000
25%,2016.0,2.000000,47.585280,-122.343280,1930.000000,1.000000,1.000000,2.949800e+04,0.000000,2.849200e+04,2.560000e+04,5402.000000,2642.000000,1.326652e+06,20.770000
50%,2016.0,4.000000,47.612360,-122.332900,1966.000000,1.000000,2.000000,4.968000e+04,0.000000,4.755400e+04,4.407800e+04,12000.000000,5965.500000,2.737456e+06,50.170000
75%,2016.0,7.000000,47.649750,-122.321770,1989.000000,1.000000,4.000000,1.060000e+05,0.000000,9.494800e+04,9.206750e+04,31820.250000,12805.750000,7.177031e+06,144.950000
max,2016.0,7.000000,47.733870,-122.258640,2015.000000,111.000000,99.000000,9.320156e+06,512608.000000,9.320156e+06,9.320156e+06,639931.000000,459748.000000,4.716139e+08,16870.980000

In [19]:
df[categorical_columns].describe()

,BuildingType,PrimaryPropertyType,Neighborhood,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType,ComplianceStatus,geometry
count,1645,1645,1645,1639,846,350,1645,1645
unique,5,22,13,55,47,39,4,1577
top,NonResidential,Small- and Mid-Sized Office,DOWNTOWN,Office,Parking,Office,Compliant,POINT (-122.29898 47.66246)
freq,1442,289,355,491,332,49,1547,8

In [20]:
df[categorical_columns].dtypes

BuildingType                    object
PrimaryPropertyType             object
Neighborhood                    object
LargestPropertyUseType          object
SecondLargestPropertyUseType    object
ThirdLargestPropertyUseType     object
ComplianceStatus                object
geometry                        object
dtype: object

In [21]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler

ohe = OneHotEncoder(sparse=False)
ss = StandardScaler()

In [22]:
X[numerical_columns] = ss.fit_transform(X[numerical_columns])

In [23]:
ohe.fit_transform(X[categorical_columns])

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [24]:
X = pd.merge(X[numerical_columns], 
          pd.DataFrame(columns = ohe.get_feature_names().tolist(),
              data = ohe.fit_transform(X[categorical_columns])),
        left_index = True, right_index = True)

In [30]:
df[categorical_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BuildingType                  1645 non-null   object
 1   PrimaryPropertyType           1645 non-null   object
 2   Neighborhood                  1645 non-null   object
 3   LargestPropertyUseType        1639 non-null   object
 4   SecondLargestPropertyUseType  846 non-null    object
 5   ThirdLargestPropertyUseType   350 non-null    object
 6   ComplianceStatus              1645 non-null   object
 7   geometry                      1645 non-null   object
dtypes: object(8)
memory usage: 102.9+ KB

In [ ]:
### isoler var num et var cat
### normaliser num
### transformer var cat (OHE ou ordinal)

In [ ]:
## bcp valeurs diff =>  favoriser ordinal encoding (enlever les 2 cols de target)

In [ ]:
# 3 preds différentes (regression...), comparer avec même score (RMSE)

In [ ]:
## possibilité de lister différents scorings à calculer en une fois => doc

In [ ]:
## essayer assembliste / random forest / svr / linearregression 
## check doc scikitlab regresseurs
## /!\ ne pas oublier normalisation

In [ ]:
## /!\ 2 targets => virer les 2 => 2 colonnes de moins pour l'ordinal encoding puis ajouter une target à la fois par training

In [ ]:
# analyse
# nettoyage (outliers + valeurs vides)
# (penser à encoder null en une autre valeur si besoin, par ex pour l'encoding, puis signifier à l'inputer que telle valeur est nulle)
# encoding
# encode > cat > -5 : OHE
#                +5 : ordinal
#         > cat >