# imports

In [1]:
# imports

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn

pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [ ]:
imp_med = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [2]:
path = './data/'
csv_path = path + 'to_input_openfoodfacts.csv'
sm_df = pd.read_csv(csv_path, low_memory=False)

# Inputing

In [19]:
### appliquer imputer différentes strategies (check distribution) avec un groupby categories
### iterative imputer / estimation du choix d'imputer selon la distribution (mean/median/most frequent...)

In [4]:
sm_df.head()

,product_name,pnns_groups_1,pnns_groups_2,code,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
0,jeunes pousses,unknown,unknown,00000000000000225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L.casei,unknown,unknown,00000000000003429145,NaN,1.4,0.9,9.8,9.80,2.7,0.1,0.04
2,Cacao,unknown,unknown,0000000000031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Filetes de pollo empanado,unknown,unknown,000000000003327986,163.9,1.9,1.0,NaN,NaN,15.3,1.1,0.44
4,Burger Meat Pollo,unknown,unknown,000000000004128579,194.0,11.0,3.9,5.7,0.05,18.0,NaN,NaN

In [5]:
main_cats = sm_df['pnns_groups_1'].unique()
main_cats

array(['unknown', 'Fat and sauces', 'Composite foods', 'Sugary snacks',
       'Fruits and vegetables', 'Fish Meat Eggs', 'Beverages',
       'Milk and dairy products', 'Cereals and potatoes', 'Salty snacks',
       'Alcoholic beverages', nan, 'sugary-snacks'], dtype=object)

In [6]:
sm_df['pnns_groups_1'].value_counts()

unknown                    1080315
Fish Meat Eggs              113360
Milk and dairy products      99555
Cereals and potatoes         76949
Beverages                    69498
Fat and sauces               63039
Composite foods              57270
Fruits and vegetables        55230
Sugary snacks                45899
Salty snacks                 27700
Alcoholic beverages          19210
sugary-snacks                    2
Name: pnns_groups_1, dtype: int64

In [7]:
sm_df['pnns_groups_1'].value_counts()

unknown                    1080315
Fish Meat Eggs              113360
Milk and dairy products      99555
Cereals and potatoes         76949
Beverages                    69498
Fat and sauces               63039
Composite foods              57270
Fruits and vegetables        55230
Sugary snacks                45899
Salty snacks                 27700
Alcoholic beverages          19210
sugary-snacks                    2
Name: pnns_groups_1, dtype: int64

In [8]:
all_cols = sm_df['pnns_groups_1'].unique().tolist()
all_cols

['unknown',
 'Fat and sauces',
 'Composite foods',
 'Sugary snacks',
 'Fruits and vegetables',
 'Fish Meat Eggs',
 'Beverages',
 'Milk and dairy products',
 'Cereals and potatoes',
 'Salty snacks',
 'Alcoholic beverages',
 nan,
 'sugary-snacks']

In [9]:
sm_df.columns

Index(['product_name', 'pnns_groups_1', 'pnns_groups_2', 'code',
       'energy-kcal_100g', 'fat_100g', 'saturated-fat_100g',
       'carbohydrates_100g', 'sugars_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g'],
      dtype='object')

In [10]:
main_cats = ['fat_100g', 'salt_100g']
complementary_cats = ['saturated-fat_100g','sodium_100g']

In [11]:
final_cats = [c for c in all_cols if c not in main_cats+complementary_cats]
final_cats

['unknown',
 'Fat and sauces',
 'Composite foods',
 'Sugary snacks',
 'Fruits and vegetables',
 'Fish Meat Eggs',
 'Beverages',
 'Milk and dairy products',
 'Cereals and potatoes',
 'Salty snacks',
 'Alcoholic beverages',
 nan,
 'sugary-snacks']

## fat / salt => mean input

In [12]:
#groupby pnns_groups_1, mean, remplir avec mean / categorie
#list1 = ["fat_100g", "salt_100g"]
main_cats

['fat_100g', 'salt_100g']

In [13]:
main_cats_grp = main_cats.append('pnns_group_1')
main_cats_grp

In [14]:
main_cats_grp = ['fat_100g', 'salt_100g', 'pnns_group_1']
main_cats_grp

['fat_100g', 'salt_100g', 'pnns_group_1']

In [15]:
# sm_df[[c for c in df.columns if c in main_cats]].head()

In [16]:
sm_df.filter(main_cats).head()

   fat_100g  salt_100g
0       NaN        NaN
1       1.4        0.1
2       NaN        NaN
3       1.9        1.1
4      11.0        NaN

In [17]:
sm_df_groupby = sm_df.groupby(by='pnns_groups_1')

In [18]:
sm_df_groupby.mean()

,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
pnns_groups_1,,,,,,,,
Alcoholic beverages,66.619878,1.290206,0.267635,7.864081,3.626928,1.400195,0.469999,0.215946
Beverages,48.412283,0.820464,0.429246,8.329317,7.094946,0.954389,0.206885,0.092242
Cereals and potatoes,294.311534,4.684030,1.020387,51.001032,3.002433,10.050230,0.682527,0.274646
Composite foods,177.046995,7.539578,2.491210,18.182893,2.565496,7.652201,1.180105,0.473079
Fat and sauces,228.787619,16.480630,4.785741,10.546215,7.180036,1.967222,2.017257,0.811976
Fish Meat Eggs,207.257507,12.748846,4.186412,2.691659,0.896183,18.925177,1.933769,0.776386
Fruits and vegetables,71.978922,1.486411,0.331087,11.226577,6.711564,2.065463,0.515616,0.208700
Milk and dairy products,223.447365,15.633708,10.129301,7.687872,5.959879,12.292904,0.873741,0.363899
Salty snacks,379.848515,29.337939,6.329597,18.591729,1.903797,8.434855,1.660792,0.667126
Sugary snacks,274.965828,7.797832,3.198125,42.446313,19.491716,3.891545,0.483837,0.197936
sugary-snacks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,201.681150,9.471510,3.250305,18.148168,4.863237,9.365741,1.386422,0.588584

In [ ]:
## faire fonction et apply par ligne ou boucler sur données uniques

In [ ]:
## utiliser index (str) de sm_df_groupby

In [48]:
#sm_df.filter(main_cats_grp).head()

# sat_fat / sodium => linearRegression

In [20]:
# IterativeImputer avec estimator=LinearRegression()
#list2 = ["saturated-fat_100g", "sodium_100g"] 
complementary_cats

['saturated-fat_100g', 'sodium_100g']

In [21]:
sm_df.filter(complementary_cats).head()

   saturated-fat_100g  sodium_100g
0                 NaN          NaN
1                 0.9         0.04
2                 NaN          NaN
3                 1.0         0.44
4                 3.9          NaN

In [19]:
sm_df_groupby.median()

,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
pnns_groups_1,,,,,,,,
Alcoholic beverages,43.0,0.00,0.00,4.00,0.09,0.20,0.00000,0.000000
Beverages,40.0,0.00,0.00,8.30,7.10,0.00,0.01000,0.004000
Cereals and potatoes,335.0,2.35,0.40,53.57,2.10,9.50,0.45000,0.180000
Composite foods,164.0,6.40,1.79,14.50,2.00,7.00,0.97500,0.390000
Fat and sauces,140.0,4.30,1.10,6.67,3.33,0.90,1.30000,0.520000
Fish Meat Eggs,188.0,10.00,2.68,0.90,0.50,19.00,1.60000,0.640000
Fruits and vegetables,49.0,0.30,0.00,7.60,3.50,1.18,0.16505,0.066040
Milk and dairy products,229.0,14.00,8.47,4.58,3.57,7.96,0.35000,0.140000
Salty snacks,408.0,26.00,3.50,6.20,1.10,6.70,1.30000,0.520000
Sugary snacks,286.0,3.70,0.90,42.00,14.00,2.42,0.12500,0.050000
sugary-snacks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,176.0,4.21,1.00,9.50,1.80,5.90,0.71425,0.286512

In [ ]:
#Reste des variables contenant des valeurs vides (sans list1, list2,  pnns_groups_1, pnns_groups_2) : 
# remplir soit avec la moyenne soit avec la mediane, en fonction de la distribution 
#- remplir avec la valeur la plus fréquente