In [2]:
# imports

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn

pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [3]:
imp_med = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [4]:
path = './data/'
csv_path = path + 'fr.openfoodfacts.org.products.csv'
df = pd.read_csv(csv_path, low_memory=False, sep='\t')

In [18]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320772 entries, 0 to 320771
Data columns (total 162 columns):
 #    Column                                      Dtype
---   ------                                      -----
 0    code                                        object
 1    url                                         object
 2    creator                                     object
 3    created_t                                   object
 4    created_datetime                            object
 5    last_modified_t                             object
 6    last_modified_datetime                      object
 7    product_name                                object
 8    generic_name                                object
 9    quantity                                    object
 10   packaging                                   object
 11   packaging_tags                              object
 12   brands                                      object
 13   brands_tags                                 object
 14   categories                                  object
 15   categories_tags                             object
 16   categories_fr                               object
 17   origins                                     object
 18   origins_tags                                object
 19   manufacturing_places                        object
 20   manufacturing_places_tags                   object
 21   labels                                      object
 22   labels_tags                                 object
 23   labels_fr                                   object
 24   emb_codes                                   object
 25   emb_codes_tags                              object
 26   first_packaging_code_geo                    object
 27   cities                                      object
 28   cities_tags                                 object
 29   purchase_places                             object
 30   stores                                      object
 31   countries                                   object
 32   countries_tags                              object
 33   countries_fr                                object
 34   ingredients_text                            object
 35   allergens                                   object
 36   allergens_fr                                object
 37   traces                                      object
 38   traces_tags                                 object
 39   traces_fr                                   object
 40   serving_size                                object
 41   no_nutriments                               float64
 42   additives_n                                 float64
 43   additives                                   object
 44   additives_tags                              object
 45   additives_fr                                object
 46   ingredients_from_palm_oil_n                 float64
 47   ingredients_from_palm_oil                   float64
 48   ingredients_from_palm_oil_tags              object
 49   ingredients_that_may_be_from_palm_oil_n     float64
 50   ingredients_that_may_be_from_palm_oil       float64
 51   ingredients_that_may_be_from_palm_oil_tags  object
 52   nutrition_grade_uk                          float64
 53   nutrition_grade_fr                          object
 54   pnns_groups_1                               object
 55   pnns_groups_2                               object
 56   states                                      object
 57   states_tags                                 object
 58   states_fr                                   object
 59   main_category                               object
 60   main_category_fr                            object
 61   image_url                                   object
 62   image_small_url                             object
 63   energy_100g                                 float64
 64   energy-from-fat_100g                        float64
 65   fat_100g                                    float64
 66   saturated-fat_100g                          float64
 67   butyric-acid_100g                           float64
 68   caproic-acid_100g                           float64
 69   caprylic-acid_100g                          float64
 70   capric-acid_100g                            float64
 71   lauric-acid_100g                            float64
 72   myristic-acid_100g                          float64
 73   palmitic-acid_100g                          float64
 74   stearic-acid_100g                           float64
 75   arachidic-acid_100g                         float64
 76   behenic-acid_100g                           float64
 77   lignoceric-acid_100g                        float64
 78   cerotic-acid_100g                           float64
 79   montanic-acid_100g                          float64
 80   melissic-acid_100g                          float64
 81   monounsaturated-fat_100g                    float64
 82   polyunsaturated-fat_100g                    float64
 83   omega-3-fat_100g                            float64
 84   alpha-linolenic-acid_100g                   float64
 85   eicosapentaenoic-acid_100g                  float64
 86   docosahexaenoic-acid_100g                   float64
 87   omega-6-fat_100g                            float64
 88   linoleic-acid_100g                          float64
 89   arachidonic-acid_100g                       float64
 90   gamma-linolenic-acid_100g                   float64
 91   dihomo-gamma-linolenic-acid_100g            float64
 92   omega-9-fat_100g                            float64
 93   oleic-acid_100g                             float64
 94   elaidic-acid_100g                           float64
 95   gondoic-acid_100g                           float64
 96   mead-acid_100g                              float64
 97   erucic-acid_100g                            float64
 98   nervonic-acid_100g                          float64
 99   trans-fat_100g                              float64
 100  cholesterol_100g                            float64
 101  carbohydrates_100g                          float64
 102  sugars_100g                                 float64
 103  sucrose_100g                                float64
 104  glucose_100g                                float64
 105  fructose_100g                               float64
 106  lactose_100g                                float64
 107  maltose_100g                                float64
 108  maltodextrins_100g                          float64
 109  starch_100g                                 float64
 110  polyols_100g                                float64
 111  fiber_100g                                  float64
 112  proteins_100g                               float64
 113  casein_100g                                 float64
 114  serum-proteins_100g                         float64
 115  nucleotides_100g                            float64
 116  salt_100g                                   float64
 117  sodium_100g                                 float64
 118  alcohol_100g                                float64
 119  vitamin-a_100g                              float64
 120  beta-carotene_100g                          float64
 121  vitamin-d_100g                              float64
 122  vitamin-e_100g                              float64
 123  vitamin-k_100g                              float64
 124  vitamin-c_100g                              float64
 125  vitamin-b1_100g                             float64
 126  vitamin-b2_100g                             float64
 127  vitamin-pp_100g                             float64
 128  vitamin-b6_100g                             float64
 129  vitamin-b9_100g                             float64
 130  folates_100g                                float64
 131  vitamin-b12_100g                            float64
 132  biotin_100g                                 float64
 133  pantothenic-acid_100g                       float64
 134  silica_100g                                 float64
 135  bicarbonate_100g                            float64
 136  potassium_100g                              float64
 137  chloride_100g                               float64
 138  calcium_100g                                float64
 139  phosphorus_100g                             float64
 140  iron_100g                                   float64
 141  magnesium_100g                              float64
 142  zinc_100g                                   float64
 143  copper_100g                                 float64
 144  manganese_100g                              float64
 145  fluoride_100g                               float64
 146  selenium_100g                               float64
 147  chromium_100g                               float64
 148  molybdenum_100g                             float64
 149  iodine_100g                                 float64
 150  caffeine_100g                               float64
 151  taurine_100g                                float64
 152  ph_100g                                     float64
 153  fruits-vegetables-nuts_100g                 float64
 154  collagen-meat-protein-ratio_100g            float64
 155  cocoa_100g                                  float64
 156  chlorophyl_100g                             float64
 157  carbon-footprint_100g                       float64
 158  nutrition-score-fr_100g                     float64
 159  nutrition-score-uk_100g                     float64
 160  glycemic-index_100g                         float64
 161  water-hardness_100g                         float64
dtypes: float64(106), object(56)
memory usage: 396.5+ MB

In [10]:
df.describe()

,no_nutriments,additives_n,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,nutrition_grade_uk,energy_100g,energy-from-fat_100g,fat_100g,saturated-fat_100g,butyric-acid_100g,caproic-acid_100g,caprylic-acid_100g,capric-acid_100g,lauric-acid_100g,myristic-acid_100g,palmitic-acid_100g,stearic-acid_100g,arachidic-acid_100g,behenic-acid_100g,lignoceric-acid_100g,cerotic-acid_100g,montanic-acid_100g,melissic-acid_100g,monounsaturated-fat_100g,polyunsaturated-fat_100g,omega-3-fat_100g,alpha-linolenic-acid_100g,eicosapentaenoic-acid_100g,docosahexaenoic-acid_100g,omega-6-fat_100g,linoleic-acid_100g,arachidonic-acid_100g,gamma-linolenic-acid_100g,dihomo-gamma-linolenic-acid_100g,omega-9-fat_100g,oleic-acid_100g,elaidic-acid_100g,gondoic-acid_100g,mead-acid_100g,erucic-acid_100g,nervonic-acid_100g,trans-fat_100g,cholesterol_100g,carbohydrates_100g,sugars_100g,sucrose_100g,glucose_100g,fructose_100g,lactose_100g,maltose_100g,maltodextrins_100g,starch_100g,polyols_100g,fiber_100g,proteins_100g,casein_100g,serum-proteins_100g,nucleotides_100g,salt_100g,sodium_100g,alcohol_100g,vitamin-a_100g,beta-carotene_100g,vitamin-d_100g,vitamin-e_100g,vitamin-k_100g,vitamin-c_100g,vitamin-b1_100g,vitamin-b2_100g,vitamin-pp_100g,vitamin-b6_100g,vitamin-b9_100g,folates_100g,vitamin-b12_100g,biotin_100g,pantothenic-acid_100g,silica_100g,bicarbonate_100g,potassium_100g,chloride_100g,calcium_100g,phosphorus_100g,iron_100g,magnesium_100g,zinc_100g,copper_100g,manganese_100g,fluoride_100g,selenium_100g,chromium_100g,molybdenum_100g,iodine_100g,caffeine_100g,taurine_100g,ph_100g,fruits-vegetables-nuts_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
count,0.0,248939.000000,248939.000000,0.0,248939.000000,0.0,0.0,2.611130e+05,857.000000,243891.000000,229554.000000,0.0,0.0,1.0,2.000000,4.000000,1.0,1.0,1.0,24.000000,23.000000,0.0,0.0,1.0,0.0,22823.000000,22859.000000,841.000000,186.000000,38.000000,78.000000,188.000000,149.000000,8.000000,24.000000,23.000000,21.000000,13.000000,0.0,1.400000e+01,0.0,0.0,0.0,143298.000000,144090.000000,243588.000000,244971.000000,72.000000,26.000000,38.000000,262.000000,4.000000,11.000000,266.000000,414.000000,200886.000000,259922.000000,27.000000,16.000000,9.000000,255510.000000,255463.000000,4133.000000,137554.000000,34.000000,7057.000000,1340.000000,918.000000,140867.000000,11154.000000,10815.000000,11729.000000,6784.000000,5240.000000,3042.000000,5.300000e+03,330.000000,2483.000000,38.000000,81.000000,24748.000000,158.000000,141050.000000,5845.000000,140462.000000,6253.000000,3929.000000,2106.000000,1620.000000,79.000000,1168.000000,20.000000,11.000000,259.000000,78.000000,29.000000,49.000000,3036.000000,165.000000,948.000000,0.0,268.000000,221210.000000,221210.000000,0.0,0.0
mean,NaN,1.936024,0.019659,NaN,0.055246,NaN,NaN,1.141915e+03,585.501214,12.730379,5.129932,NaN,NaN,7.4,6.040000,36.136182,18.9,8.1,3.0,10.752667,10.673913,NaN,NaN,61.0,NaN,10.425055,6.312493,3.182103,2.250285,3.186553,1.635462,16.229144,3.823819,0.057000,0.153842,0.061567,40.192857,25.123077,NaN,1.357143e-06,NaN,NaN,NaN,0.073476,0.020071,32.073981,16.003484,11.841667,2.878846,25.897368,6.354084,24.325000,12.163636,31.925000,49.790389,2.862111,7.075940,4.658148,2.506250,0.021678,2.028624,0.798815,7.838105,0.000397,0.518715,0.000008,0.056705,0.034219,0.023367,0.325574,0.259007,0.020303,0.023378,0.006898,0.205856,8.938696e-05,0.121290,0.072138,0.013123,0.119052,0.424635,0.092638,0.125163,0.617282,0.003652,0.534143,0.007950,0.025794,0.003014,0.012161,0.003126,0.001690,0.000401,0.000427,1.594563,0.145762,6.425698,31.458587,15.412121,49.547785,NaN,341.700764,9.165535,9.058049,NaN,NaN
std,NaN,2.502019,0.140524,NaN,0.269207,NaN,NaN,6.447154e+03,712.809943,17.578747,8.014238,NaN,NaN,NaN,0.226274,24.101433,NaN,NaN,NaN,4.019993,3.379647,NaN,NaN,NaN,NaN,17.076167,10.832591,5.607988,7.971418,13.927752,1.978192,17.512632,6.494183,0.025534,0.029160,0.010597,25.175674,26.010496,NaN,4.972452e-07,NaN,NaN,NaN,1.540223,0.358062,29.731719,22.327284,13.993859,6.290341,30.015451,14.386132,17.793515,8.372129,24.704434,33.212338,12.867578,8.409054,2.976340,2.186769,0.003072,128.269454,50.504428,10.959671,0.073278,2.561144,0.000360,0.694039,1.031398,2.236451,2.474306,1.277026,0.339262,1.206822,0.335163,5.132250,5.514738e-03,0.737912,1.475120,0.040660,0.189486,12.528768,0.149725,3.318263,12.058090,0.214408,13.498653,0.080953,0.914247,0.028036,0.067952,0.104503,0.006697,0.001118,0.001285,6.475588,0.172312,2.047841,31.967918,3.753028,18.757932,NaN,425.211439,9.055903,9.183589,NaN,NaN
min,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000e+00,0.000000,0.000000,0.000000,NaN,NaN,7.4,5.880000,0.044730,18.9,8.1,3.0,0.064000,5.200000,NaN,NaN,61.0,NaN,0.000000,0.000000,0.000000,0.000000,0.050000,0.041000,0.050000,0.090000,0.007000,0.095000,0.043307,1.000000,1.080000,NaN,1.000000e-06,NaN,NaN,NaN,-3.570000,0.000000,0.000000,-17.860000,0.000000,0.000000,0.000000,0.000000,0.100000,1.500000,0.000000,0.000000,-6.700000,-800.000000,0.920000,0.300000,0.015500,0.000000,0.000000,0.000000,-0.000340,0.000000,0.000000,0.000000,0.000000,-0.002100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-2.000000,-2.000000,0.000008,0.000006,0.000000,0.000002,0.000000,0.000000,-0.000260,0.000000,0.000000,-6.896552,0.000000,0.000000,-0.000002,0.000007,0.000005,0.000000,0.000000,0.001800,0.000000,0.000000,8.000000,6.000000,NaN,0.000000,-15.000000,-15.000000,NaN,NaN
25%,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,3.770000e+02,49.400000,0.000000,0.000000,NaN,NaN,7.4,5.960000,34.661183,18.9,8.1,3.0,7.275000,7.100000,NaN,NaN,61.0,NaN,0.000000,0.000000,0.600000,0.068750,0.200000,0.171500,1.850000,0.437000,0.046250,0.130000,0.051181,27.000000,6.900000,NaN,1.062500e-06,NaN,NaN,NaN,0.000000,0.000000,6.000000,1.300000,2.100000,0.200000,0.950000,0.000000,16.525000,5.400000,4.500000,18.350000,0.000000,0.700000,2.150000,0.300000,0.021600,0.063500,0.025000,0.000000,0.000000,0.001225,0.000001,0.001800,0.000006,0.000000,0.004000,0.002720,0.003077,0.000255,0.000030,0.000042,7.200000e-07,0.000006,0.000417,0.001500,0.017320,0.107000,0.001368,0.000000,0.094000,0.000000,0.021000,0.001150,0.000177,0.000000,0.000018,0.000005,0.000011,0.000020,0.000015,0.015500,0.035000,6.300000,0.000000,12.000000,32.000000,NaN,98.750000,1.000000,1.000000,NaN,NaN
50%,NaN,1.000000,0.000000,NaN,0.000000,NaN,NaN,1.100000e+03,300.000000,5.000000,1.790000,NaN,NaN,7.4,6.040000,47.600000,18.9,8.1,3.0,12.850000,12.600000,NaN,NaN,61.0,NaN,4.000000,2.220000,1.800000,0.117500,0.500000,0.800000,10.050000,0.647000,0.061000,0.155000,0.062992,31.000000,11.000000,NaN,1.250000e-06,NaN,NaN,NaN,0.000000,0.000000,20.600000,5.710000,8.100000,0.250000,13.000000,0.100000,29.000000,13.500000,35.900000,59.750000,1.500000,4.760000,4.200000,1.950000,0.022000,0.581660,0.229000,5.000000,0.000000,0.005261,0.000001,0.005200,0.000025,0.000000,0.012000,0.014167,0.005357,0.000700,0.000052,0.000114,1.920000e-06,0.000014,0.001639,0.003185,0.036000,0.180000,0.014600,0.035000,0.206000,0.001010,0.075000,0.003700,0.000417,0.001000,0.000060,0.000022,0.000023,0.000039,0.000034,0.021000,0.039000,7.200000,23.000000,15.000000,50.000000,NaN,195.750000,10.000000,9.000000,NaN,NaN
75%,NaN,3.000000,0.000000,NaN,0.000000,NaN,NaN,1.674000e+03,898.000000,20.000000,7.140000,NaN,NaN,7.4,6.120000,49.075000,18.9,8.1,3.0,13.375000,13.050000,NaN,NaN,61.0,NaN,10.710000,7.140000,3.200000,0.604000,0.715750,3.300000,23.000000,3.600000,0.068500,0.170000,0.066929,68.000000,40.500000,NaN,1.250000e-06,NaN,NaN,NaN,0.000000,0.020000,58.330000,24.000000,16.150000,1.400000,52.075000,4.175000,36.800000,16.950000,50.000000,70.000000,3.600000,10.000000,7.100000,4.750000,0.024000,1.374140,0.541000,12.000000,0.000107,0.140000,0.000003,0.012000,0.000100,0.003700,0.402000,0.300000,0.009091,0.001500,0.000070,0.000214,4.690000e-06,0.000041,0.004167,0.007100,0.143000,0.341000,0.071750,0.106000,0.357000,0.002400,0.141000,0.007500,0.001000,0.002000,0.000450,0.000061,0.000068,0.000074,0.000103,0.043000,0.400000,7.400000,51.000000,15.000000,64.250000,NaN,383.200000,16.000000,16.000000,NaN,NaN
max,NaN,31.000000,2.000000,NaN,6.000000,NaN,NaN,3.251373e+06,3830.000000,714.290000,550.000000,NaN,NaN,7.4,6.200000,49.300000,18.9,8.1,3.0,15.400000,14.600000,NaN,NaN,61.0,NaN,557.140000,98.000000,60.000000,75.000000,85.000000,12.000000,71.000000,25.000000,0.090000,0.203200,0.080000,75.000000,76.000000,NaN,2.500000e-06,NaN,NaN,NaN,369.000000,95.238000,2916.670000,3520.000000,92.800000,23.200000,101.000000,74.500000,39.200000,27.500000,87.800000,100.000000,5380.000000,430.000000,10.700000,5.800000,0.025000,64312.800000,25320.000000,97.900000,26.700000,15.000000,0.030000,15.100000,31.250000,716.981100,161.000000,42.500000,21.428571,92.600000,23.076923,178.571429,4.000000e-01,6.000000,60.000000,0.250000,1.250000,1870.370000,0.589000,694.737000,559.459000,50.000000,657.143000,4.000000,37.600000,0.700000,0.560000,3.571429,0.030000,0.003760,0.014700,42.280000,0.423000,8.400000,100.000000,25.000000,100.000000,NaN,2842.000000,40.000000,40.000000,NaN,NaN

In [6]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,packaging,packaging_tags,brands,brands_tags,categories,categories_tags,categories_fr,origins,origins_tags,manufacturing_places,manufacturing_places_tags,labels,labels_tags,labels_fr,emb_codes,emb_codes_tags,first_packaging_code_geo,cities,cities_tags,purchase_places,stores,countries,countries_tags,countries_fr,ingredients_text,allergens,allergens_fr,traces,traces_tags,traces_fr,serving_size,no_nutriments,additives_n,additives,additives_tags,additives_fr,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_from_palm_oil_tags,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,ingredients_that_may_be_from_palm_oil_tags,nutrition_grade_uk,nutrition_grade_fr,pnns_groups_1,pnns_groups_2,states,states_tags,states_fr,main_category,main_category_fr,image_url,image_small_url,energy_100g,energy-from-fat_100g,fat_100g,saturated-fat_100g,butyric-acid_100g,caproic-acid_100g,caprylic-acid_100g,capric-acid_100g,lauric-acid_100g,myristic-acid_100g,palmitic-acid_100g,stearic-acid_100g,arachidic-acid_100g,behenic-acid_100g,lignoceric-acid_100g,cerotic-acid_100g,montanic-acid_100g,melissic-acid_100g,monounsaturated-fat_100g,polyunsaturated-fat_100g,omega-3-fat_100g,alpha-linolenic-acid_100g,eicosapentaenoic-acid_100g,docosahexaenoic-acid_100g,omega-6-fat_100g,linoleic-acid_100g,arachidonic-acid_100g,gamma-linolenic-acid_100g,dihomo-gamma-linolenic-acid_100g,omega-9-fat_100g,oleic-acid_100g,elaidic-acid_100g,gondoic-acid_100g,mead-acid_100g,erucic-acid_100g,nervonic-acid_100g,trans-fat_100g,cholesterol_100g,carbohydrates_100g,sugars_100g,sucrose_100g,glucose_100g,fructose_100g,lactose_100g,maltose_100g,maltodextrins_100g,starch_100g,polyols_100g,fiber_100g,proteins_100g,casein_100g,serum-proteins_100g,nucleotides_100g,salt_100g,sodium_100g,alcohol_100g,vitamin-a_100g,beta-carotene_100g,vitamin-d_100g,vitamin-e_100g,vitamin-k_100g,vitamin-c_100g,vitamin-b1_100g,vitamin-b2_100g,vitamin-pp_100g,vitamin-b6_100g,vitamin-b9_100g,folates_100g,vitamin-b12_100g,biotin_100g,pantothenic-acid_100g,silica_100g,bicarbonate_100g,potassium_100g,chloride_100g,calcium_100g,phosphorus_100g,iron_100g,magnesium_100g,zinc_100g,copper_100g,manganese_100g,fluoride_100g,selenium_100g,chromium_100g,molybdenum_100g,iodine_100g,caffeine_100g,taurine_100g,ph_100g,fruits-vegetables-nuts_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,0000000003087,http://world-fr.openfoodfacts.org/produit/0000000003087/farine-de-ble-noir-ferme-t-y-r-nao,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,NaN,NaN,Ferme t'y R'nao,ferme-t-y-r-nao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:FR,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"en:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded","en:to-be-completed,en:nutrition-facts-to-be-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded","A compléter,Informations nutritionnelles à compléter,Ingrédients à compléter,Date limite à compléter,Caractéristiques à compléter,Catégories à compléter,Marques complétées,Emballage à compléter,Quantité complétée,Nom du produit complete,Photos à valider,Photos envoyées",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000004530,http://world-fr.openfoodfacts.org/produit/0000000004530/banana-chips-sweetened-whole,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,en:united-states,États-Unis,"Bananas, vegetable oil (coconut oil, corn oil and/or palm oil) sugar, natural banana flavor.",NaN,NaN,NaN,NaN,NaN,28 g (1 ONZ),NaN,0.0,[ bananas -> en:bananas ] [ vegetable-oil -> en:vegetable-oil ] [ oil -> en:oil ] [ coconut-oil -> en:coconut-oil ] [ oil -> en:oil ] [ corn-oil-and-or-palm-oil-sugar -> en:corn-oil-and-or-palm-oil-sugar ] [ oil-and-or-palm-oil-sugar -> en:oil-and-or-palm-oil-sugar ] [ and-or-palm-oil-sugar -> en:and-or-palm-oil-sugar ] [ or-palm-oil-sugar -> en:or-palm-oil-sugar ] [ palm-oil-sugar -> en:palm-oil-sugar ] [ oil-sugar -> en:oil-sugar ] [ sugar -> en:sugar ] [ natural-banana-flavor -> en:natural-banana-flavor ] [ banana-flavor -> en:banana-flavor ] [ flavor -> en:flavor ],NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,d,NaN,NaN,"en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-to-be-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-uploaded","en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-to-be-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-uploaded","A compléter,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,en:Packaging-code-to-be-completed,Caractéristiques à compléter,Catégories à compléter,Marques à compléter,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à envoyer",NaN,NaN,NaN,NaN,2243.0,NaN,28.57,28.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.018,64.29,14.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.6,3.57,NaN,NaN,NaN,0.00000,0.000,NaN,0.0,NaN,NaN,NaN,NaN,0.0214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,0.00129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,0000000004559,http://world-fr.openfoodfacts.org/produit/0000000004559/peanuts-torn-glasser,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,NaN,NaN,Torn & Glasser,torn-glasser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,en:united-states,États-Unis,"Peanuts, wheat flour, sugar, rice flour, tapioca starch, salt, leavening (ammonium bicarbonate, baking soda), soy sauce (water, soybeans, wheat, salt), potato starch.",NaN,NaN,NaN,NaN,NaN,28 g (0.25 cup),NaN,0.0,[ peanuts -> en:peanuts ] [ wheat-flour -> en:wheat-flour ] [ flour -> en:flour ] [ sugar -> en:sugar ] [ rice-flour -> en:rice-flour ] [ flour -> en:flour ] [ tapioca-starch -> en:tapioca-starch ] [ starch -> en:starch ] [ salt -> en:salt ] [ leavening -> en:leavening ] [ ammonium-bicarbonate -> en:ammonium-bicarbonate ] [ bicarbonate -> en:bicarbonate ] [ baking-soda -> en:baking-soda ] [ soda -> en:soda ] [ soy-sauce -> en:soy-sauce ] [ sauce -> en:sauce ] [ water -> en:water ] [ soybeans -> en:soybeans ] [ wheat -> en:wheat ] [ salt -> en:salt ] [ potato-starch -> en:potato-starch ] [ starch -> en:starch ],NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,b,NaN,NaN,"en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-uploaded","en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-uploaded","A compléter,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,en:Packaging-code-to-be-completed,Caractéristiques à compléter,Catégories à compléter,Marques complétées,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à envoyer",NaN,NaN,NaN,NaN,1941.0,NaN,17.86,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000,60.71,17.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.1,17.86,NaN,NaN,NaN,0.63500,0.250,NaN,0.0,NaN,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.071,NaN,0.00129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0000000016087,http://world-fr.openfoodfacts.org/produit/0000000016087/organic-salted-nut-mix-grizzlies,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,NaN,NaN,Grizzlies,grizzlies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,en:united-states,États-Unis,"Organic hazelnuts, organic cashews, organic walnuts almonds, organic sunflower oil, sea salt.",NaN,NaN,NaN,NaN,NaN,28 g (0.25 cup),NaN,0.0,[ organic-hazelnuts -> en:organic-hazelnuts ] [ hazelnuts -> en:hazelnuts ] [ organic-cashews -> en:organic-cashews ] [ cashews -> en:cashews ] [ organic-walnuts-almonds -> en:organic-walnuts-almonds ] [ walnuts-almonds -> en:walnuts-almonds ] [ almonds -> en:almonds ] [ organic-sunflower-oil -> en:organic-sunflower-oil ] [ sunflower-oil -> en:sunflower-oil ] [ oil -> en:oil ] [ sea-salt -> en:sea-salt ] [ salt -> en:salt ],NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,d,NaN,NaN,"en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-uploaded","en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-uploaded","A compléter,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,en:Packaging-code-to-be-completed,Caractéristiques à compléter,Catégories à compléter,Marques complétées,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à envoyer",NaN,NaN,NaN,NaN,2540.0,NaN,57.14,5.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.86,3.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.1,17.86,NaN,NaN,NaN,1.22428,0.482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.143,NaN,0.00514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,0000000016094,http://world-fr.openfoodfacts.org/produit/0000000016094/organic-polenta-bob-s-red-mill,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,NaN,NaN,Bob's Red Mill,bob-s-red-mill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,en:united-states,États-Unis,Organic polenta,NaN,NaN,NaN,NaN,NaN,35 g (0.25 cup),NaN,0.0,[ organic-polenta -> en:organic-polenta ] [ polenta -> en:polenta ],NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-to-be-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-uploaded","en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-to-be-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-uploaded","A compléter,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,en:Packaging-code-to-be-completed,Caractéristiques à compléter,Catégories à compléter,Marques complétées,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à envoyer",NaN,NaN,NaN,NaN,1552.0,NaN,1.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.7,8.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(320772, 162)

In [ ]:
#df.groupby(['Courses'])['Courses'].count()

In [11]:
# count distinct values
df.countries.nunique()

1434

In [12]:
# show values
df.countries.unique().tolist()

['en:FR',
 'US',
 'France',
 'en:GB',
 'France, US',
 'Canada',
 'United Kingdom',
 'en:CH',
 'en:ES',
 'Deutschland',
 'en:SI',
 'en:DE',
 'en:IT',
 'en:RO',
 'España',
 'en:AU',
 'en:PT',
 'United States',
 'Germany',
 'Usa',
 'France,Royaume-Uni',
 'UK,France',
 'France,Belgique,Pays-Bas,Royaume-Uni',
 'France,United Kingdom',
 'en:GP',
 'France,UK',
 'États-Unis',
 'Royaume-Uni,France',
 'en:CA',
 nan,
 'en:US,United Kingdom',
 'Switzerland',
 'en:US',
 'en:CA, US',
 'Nederland',
 'en:AU, en:france',
 'Australia',
 'France,Suisse,États-Unis,Canada',
 'États-Unis, en:france, US',
 'Ireland',
 'United Kingdom, US',
 'en:RE, en:france',
 'United States, en:france',
 'en:TW',
 'en:AU, Suisse',
 'Deutschland, en:france',
 'Suisse',
 'en:BR',
 'Belgique,France',
 'en:DO',
 'en:FR, US',
 'Belgique,France,Pays-Bas,Royaume-Uni',
 'France,United States',
 'Australie, US',
 'USA',
 'en:SA',
 'Saudi Arabia',
 'en:AE',
 'en:IQ',
 'en:KW',
 'Republica Moldova',
 'Belgium',
 'en:NC',
 'Singapore',
 'en:FI',
 'en:SG',
 'Australia, US',
 'France, Suisse',
 'en:FR, Suisse',
 'France,États-Unis',
 'Singapore,New Zealand,Thailand,Australia, US',
 'en:PF',
 'en:PA',
 'en:US, en:france',
 'en:CR',
 'en:MX',
 'en:GB, US',
 'Pays-Bas, US',
 'Pays-Bas',
 'Spain,United Kingdom,Scotland',
 'en:PF, US',
 'en:TH',
 '中華民國',
 'United states',
 'México',
 'ประเทศไทย',
 'en:CN',
 'en:LU',
 'en:LB',
 'Mexico',
 'US,Switzerland',
 'Deutschland,Vereinigte Staaten von Amerika',
 'United States,Deutschland',
 'France,États-Unis,Suisse',
 'Belgium,United States,Switzerland',
 'Switzerland,United States',
 'Spanien,Denmark, US',
 'België,Nederland, US',
 'en:BE',
 'Belgium, Suisse',
 'Frankreich,Deutschland',
 'en:MY, US',
 'en:GY, US',
 'Etats-Unis',
 'Serbia',
 'en:MQ',
 'United Arab Emirates',
 'en:BB',
 'en:AW',
 'Hong Kong',
 'en:NO',
 'en:HT',
 'El Salvador',
 'en:BH, US',
 'France,Italie',
 'en:TW, US',
 'United Kingdom, en:france',
 'Belgique, en:france',
 'Réunion',
 'en:MA',
 'Oman',
 'en:KR',
 'en:HK',
 'United Kingdom,France',
 'en:TT',
 'Niederlande, US',
 'Chile',
 'Cuba',
 'en:AU, US',
 'Canada, US',
 'France,United Kingdom,United States',
 'spain',
 'United States, en:france, en:switzerland',
 'UK',
 'en:IT, US',
 'France,Switzerland',
 'UK, Suisse',
 'Belgique',
 'Philippines',
 'en:CH, US',
 'en:ES, US',
 'España, Estados Unidos',
 'Panama, US',
 'Canada,United States',
 'Canada,États-Unis',
 'Australia,France,United Kingdom',
 'France,United Kingdom, US',
 'Brasil',
 'en:BE, Suisse',
 'France,Belgique,Royaume-Uni,Pays-Bas',
 'Österreich',
 'Sweden',
 'en:GN',
 'UK,France,US',
 'United States of America',
 'Costa Rica, US',
 'en:IL, US',
 'China,Switzerland',
 'en:RU',
 'en:PM',
 'en:CA, en:france',
 'en:DZ',
 'Saint Pierre and Miquelon',
 'Canada, en:france',
 'en:NL, US',
 'Québec',
 'en:CZ',
 'Italia',
 'France,Canada',
 'Canada, en:united-states',
 'Canada,France',
 'Québec, Canada',
 'Canada, en:france, en:switzerland',
 'Belgique,Canada,France,Suisse',
 'UK,Czech',
 'fr:Québec',
 'en:france',
 'France,Saint Pierre and Miquelon',
 'Nouvelle-Calédonie',
 'Canada,Portugal',
 'Saint-Pierre-et-Miquelon',
 'Germany,Switzerland',
 'Франция,Россия,Испания,Великобритания',
 'en:MU',
 'Indonésie',
 'France, en:switzerland',
 'Arménie',
 'France,Royaume-Uni, Suisse',
 'Royaume-Uni',
 'France,New Zealand',
 'en:CI',
 'China, Suisse',
 'Österreich, Suisse',
 'en:PL',
 'United States,Canada',
 'Belgique,France,Royaume-Uni,Pays-Bas',
 'France,Suisse,États-Unis',
 'en:GR',
 'en:MX, US',
 'UK,Spain',
 'الكويت',
 'United States, en:india, en:united-kingdom',
 'United Kingdom, Suisse',
 'UK,France,Belgium',
 'Taiwan',
 'Belgium,France,Netherlands,United Kingdom',
 'Singapore, US',
 'en:IN',
 'en:EC',
 'Turkey',
 'FR',
 'China',
 'Cambodia',
 'France,Australia',
 'en:US, US',
 'Chile, US',
 'en:NC, US',
 'en:HK, US',
 '香港, US',
 'Canada,France,États-Unis',
 'Belgique,France,Royaume-Uni',
 'en:CL, US',
 'Norway',
 'Italy',
 'en:DE, en:france',
 'Netherlands',
 'en:GR, US',
 'en:AR',
 'France,Pays-Bas',
 'en:SE',
 'France,United States,Switzerland',
 'Algérie',
 'France,Pays-Bas,Royaume-Uni',
 'Czech Republic,United Kingdom',
 'European Union',
 'en:AT',
 'en:JO',
 'Australia,Indonesia,United States',
 'Australia,Indonesia',
 '香港,美国',
 'en:JP',
 'en:IL',
 'France,Royaume-Uni,Pays-Bas',
 'France,Belgique,Royaume-Uni',
 'en:IE',
 'Colombia',
 'en:IT, en:france',
 'United States,United Kingdom,UK',
 'Vereinigte Staaten von Amerika',
 'Burundi',
 'en:QA, en:france',
 'en:TN',
 'Denmark,Norway,Sweden',
 'Danemark',
 'Polynésie française',
 'الجزائر, en:france',
 'uk',
 'en:CL',
 'La Réunion, France',
 'en:NL',
 'France,Guyane',
 '日本',
 'Denmark',
 'Belgique,France,Pays-Bas',
 'en:BG',
 'en:HU',
 'en:RE',
 'Australia,United States',
 'La Réunion',
 'Pérou',
 'Россия',
 'Tunisie, en:france',
 'Puerto Rico',
 'France,Suisse',
 'France,Belgique, Suisse',
 'Belgique,France, Suisse',
 'Suisse,Belgique, en:france',
 'Belgique,États-Unis',
 'France,USA',
 'en:MC',
 'en:SG, US',
 'Portugal',
 'en:NG',
 'Guyane',
 'en:HN',
 'Spain',
 'Saint Pierre and Miquelon, en:france, en:belgium',
 'en:EG',
 'Costa Rica',
 'România',
 'India',
 'United Kingdom,Cyprus',
 'en:VE',
 'Japan',
 'en:PH',
 'en:AN, en:france',
 'South Africa',
 'en:AT, US',
 'Australia,Philippines',
 'Aruba',
 'en:ES, Suisse',
 'Lebanon',
 'France,Japon',
 'en:CI, US',
 'Algérie, en:france',
 'Mongolia',
 'en:MM',
 'India, en:france',
 'en:BH',
 'França,Portugal,Reino Unido',
 'France,Suriname,United Kingdom,Guadeloupe,Greece,French Guiana',
 'Romania',
 'Pakistan',
 'Belgium, US',
 'Qatar',
 'Chili,France,Espagne,Suisse,Royaume-Uni',
 'CANADA',
 'Belgique,France,États-Unis',
 'France,Belgium',
 'Cameroun',
 'Martinique',
 'Virgin Islands of the United States, US',
 'en:PK',
 'belgium',
 'Schweiz',
 'Irland',
 'en:ID',
 'France,Royaume-Uni, US',
 'United Kingdom,United States',
 'Suisse, en:france',
 'Guadeloupe',
 'Maroc',
 'Perú',
 'Austria',
 'en:DK',
 'Danemark,Royaume-Uni,France',
 'en:EU',
 'en:BE, en:france',
 'United Kingdom,Spain,Portugal,Sweden,Finland',
 'en:SK',
 'United Kingdom,Lithuania',
 'en:CO',
 '日本, en:france',
 'South Korea',
 'United Kingdom,Spain,Portugal',
 'fr:Pologne',
 'Republic of Ireland',
 'Sénégal',
 'France,Sénégal',
 'Sénégal, en:france',
 'Spanien',
 'Morocco',
 'Marruecos',
 "Côte d'Ivoire",
 'Tunisie',
 'Union européenne',
 'Czech Republic',
 'Luxembourg, en:france',
 'Germany,Spain',
 'العراق',
 'Senegal',
 'Italie',
 'Russia',
 'Togo',
 'Royaume-Uni,france',
 'Poland',
 'Islande',
 'Suède',
 'Germany,switzerland',
 'Allemagne,suisse',
 'Allemagne,Suisse',
 'Allemagne,Belgique',
 'Belgique,Allemagne',
 'Belgien,Deutschland',
 'Allemagne,belgique',
 'Belgique,France,Allemagne,suisse',
 'Germany,United Kingdom,United States',
 'Deutschland,Vereinigtes Königreich,Vereinigte Staaten von Amerika',
 'Germany,Netherlands,Austria',
 'Österreich,Deutschland,Niederlande',
 'Austria,Germany,Netherlands',
 'Egypt',
 'Germany,Australia',
 'Australia,Germany',
 '대한민국',
 'Allemagne',
 'Italien',
 '香港',
 'United States,spain',
 'Ungaria,România,Regatul Unit al Marii Britanii și al Irlandei de Nord',
 'Ελλάδα',
 'Germany,de:Weltweit,Worldwide',
 'Iraq',
 'UK,France,UK',
 'UK,France,Angleterre',
 'Россия,Союз Советских Социалистических Республик',
 'Brésil',
 'global market',
 'الإمارات العربية المتحدة',
 'Ukraine,colombia,Czech,all over the world',
 'Russia,Soviet Union',
 'België',
 'Ísland',
 'World',
 'Dinamarca,França,Itália,Países Baixos,Polónia,Portugal,Espanha',
 'world',
 'Gulf countries,السعودية',
 'Türkiye',
 'France,Chili',
 'السعودية',
 'en:RS',
 'France,Allemagne,Espagne',
 'Francia,España',
 'France,Allemagne',
 'Hungary',
 'France,Allemagne,Roumanie,Royaume-Uni,Scotland',
 'Alemanha,Portugal,Espanha',
 'Deutschland,Italien',
 'France,Germany',
 'Deutschland,Portugal',
 'France,Allemagne,Suisse',
 'en:DE, US',
 'en:BE, US',
 'Deutschland, US',
 'España, Suiza',
 'Allemagne,France',
 'France,Portugal,Espagne',
 'united kingdom',
 'Germany,Portugal,Spain',
 'Portugal,Alemanha,Reino Unido,Finlândia,Suécia,Dinamarca,Itália,Espanha',
 'France,Maroc',
 'Belgium, en:france',
 'Bulgaria',
 'France, en:switzerland, en:reunion',
 'République tchèque,France',
 'France,Espagne',
 'en:UA',
 'Portugal,España',
 'França,Portugal',
 'España, en:france',
 'Frankreich,Deutschland,Italien',
 'France,Spain',
 'Scotland,United Kingdom',
 'Germany, en:france',
 'Frankreich,Deutschland,Schweiz',
 'France,Slovenia',
 'Austria, España',
 'France,Suède',
 'Deutschland,Österreich',
 'Belgien,Frankreich,Deutschland',
 'France,Portugal',
 'portugal',
 'United Kingdom,Scotland, en:france',
 'France,Allemagne,Italie,Suisse',
 'Frankreich,Deutschland,Spanien',
 'Spain,France',
 'Deutschland,Spanien',
 'Alemania,España',
 'Spain,United Kingdom',
 'France,Vereinigtes Königreich,Allemagne',
 'România,Romania',
 'Spain,Germany',
 'France,Allemagne,Portugal,Espagne',
 'Autriche,République tchèque,France,Allemagne',
 'Österreich,Tschechien,Frankreich,Deutschland',
 'Deutschland,Vereinigtes Königreich',
 'Luxembourg',
 'Deutschland,Österreich,Frankreich',
 'Germany,Spain, en:france',
 'Nederland,Frankrijk',
 'France,en:Scotland',
 'Bélgica,França,Alemanha,Itália,Países Baixos,Portugal,Espanha',
 'Belgique,France,Allemagne,Italie,Pays-Bas,Portugal,Espagne',
 'Switzerland,United Kingdom',
 'Autriche,France,Allemagne,Italie,Suisse',
 'Germany,France',
 'Espagne',
 'Belgium,France,Germany,Ireland,Netherlands,Portugal,Spain,United Kingdom',
 'France,Belgique',
 'Espagne,France',
 'França,Portugal,Espanha',
 'en:AL',
 'France,Allemagne,Royaume-Uni',
 'Nigeria',
 'Portugal,Espanha',
 'Poland,United Kingdom',
 'Belgique,France,Allemagne,Italie,Pays-Bas',
 'France,Italie,Suisse',
 'Francia,Portugal,España',
 'United Kingdom,Scotland',
 'France,Pays-Bas,Allemagne,Espagne',
 'en:ES, en:france',
 'France,77-PROVINS',
 'Ireland,United Kingdom, en:france',
 'en:MT',
 'España,Reino Unido',
 'en:HR',
 'Belgium,France',
 'Finland',
 'Belgique,France,Allemagne,Pays-Bas,Portugal,Espagne',
 'en:IE, en:france',
 'Belgium,Czech Republic, en:france',
 'Francia,Italia',
 'en:CH, en:france',
 'France, en:belgium',
 'France,Suisse,Allemagne',
 'Switzerland,United States, en:france',
 'Portugal,Espanha,Reino Unido',
 'Niederlande',
 'Dinamarca,Polónia,Portugal,Espanha',
 'Belgium,Netherlands',
 'Deutschland,Schweiz',
 'Schweiz,Österreich',
 'Slovenija',
 'Slovenia',
 'Frankrijk',
 'Portugal,Suécia',
 'Pays-Bas,France',
 'Australia,France',
 'Pays-Bas, en:france',
 'france',
 'Belgique, Suisse',
 'Belgium,Luxembourg',
 'Bulgarie',
 'Polska',
 'Brazil',
 'Australia, en:france',
 'Česko',
 'Україна',
 'Tschechien,Deutschland',
 'en:MW',
 'France,Guadeloupe',
 'Réunion, en:france',
 'Nouvelle-Calédonie, en:france',
 'Portugal, en:france',
 'Guyane, en:france',
 'Saint-Pierre-et-Miquelon, en:france',
 'France, en:switzerland, en:brazil, en:canada, en:belgium',
 'Belgique,France,Italie,Maroc,Suisse,Royaume-Uni',
 'France, en:switzerland, en:belgium',
 'Algérie,Belgique,Canada,France,Polynésie française,Allemagne,Irlande,Italie,Liban,Luxembourg,Mali,Martinique,Maroc,Pays-Bas,Nouvelle-Calédonie,Portugal,La Réunion,Espagne,Suisse,Tunisie,Royaume-Uni,États-Unis',
 'Belgique,France,Suisse, en:germany',
 'Algerien,Belgien,Kanada,Frankreich,Deutschland,Italien,Mali,Martinique,Spanien,Schweiz',
 'France, en:belgium, en:switzerland',
 'France, en:denmark, en:switzerland, en:belgium',
 'Guadeloupe, en:france',
 'Polynésie française, Suisse',
 'France, en:belgium, en:switzerland, en:reunion',
 'France,Monaco, en:switzerland',
 'Belgique,France,La Réunion,Suisse',
 'France,La Réunion',
 'Belgique,France,Polynésie française,Martinique,Suisse',
 'Gabon',
 'Guadeloupe,France',
 'French Guiana, en:france',
 'France,Saint-Pierre-et-Miquelon,Suisse',
 'France, en:reunion, en:switzerland',
 'Frankreich,Deutschland, en:switzerland',
 'Danemark,France',
 'Казахстан',
 'Belgique,France,Suisse',
 'Suisse,France',
 'France,Belgique,Luxembourg',
 'France,Luxembourg',
 'en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded',
 'en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded',
 'en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded',
 'en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded',
 'en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded',
 'en:to-be-completed,en:nutrition-facts-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded',
 'Guyane,France',
 'Mali,france',
 'France,Gabon',
 'Belgique,France,Espagne,Suisse',
 'Algeria',
 'Royaume-Uni,France, en:denmark, Suisse',
 'Deutschland, en:switzerland',
 'Tunisia, en:france',
 'République du Congo',
 'Belgique,France,Allemagne,Suisse',
 'États-Unis, en:france',
 'الجزائر',
 'France,Allemagne,Portugal,Suisse',
 'France,Espagne, Suisse',
 'en:MY',
 'Belgium,France,Switzerland',
 'Austria,France,Germany,Italy,Netherlands,Switzerland',
 'France,Tunisie',
 'Dánia,Franciaország,Portugália,Spanyolország,Nagy-Britannia,Magyarország, en:switzerland',
 'Dánia,Franciaország,Németország,Portugália,Spanyolország,Nagy-Britannia,Magyarország, en:switzerland, en:belgium',
 'Dánia,Svájc,Nagy-Britannia,Magyarország, en:france, Suisse',
 'Danemark,France,Royaume-Uni',
 'Suisse,Royaume-Uni,France, en:denmark, en:belgium',
 'Frankreich,Deutschland,Mauritius,Espagne,Royaume-Uni',
 'Danemark,France,Espagne, Suisse',
 'France,Royaume-Uni, en:switzerland',
 'en:AE, Suisse',
 'Belgique,France,Guyane',
 'France, en:reunion',
 'Belgique,France,Mali,La Réunion,Suisse,Royaume-Uni',
 'Belgique, en:france, Suisse',
 'United Kingdom, en:france, Suisse',
 'Франция,Россия',
 'Switzerland, en:france',
 'France, en:switzerland, en:belgium, en:united-kingdom',
 'France,Pays-Bas,Suisse',
 'en:GF',
 'France, en:switzerland, en:belgium, en:reunion, en:morocco',
 'France, en:belgium, Suisse',
 'Suisse,France, en:belgium, en:morocco, en:spain',
 'Portugal, en:denmark',
 'en:BE, en:france, Suisse',
 'France,Suisse, en:belgium',
 'Frankreich',
 'Magyarország',
 'en:IT, Suisse',
 'Danmark',
 'Belgique,France, en:switzerland',
 'España, en:denmark, Suisse',
 'France,Aix-en-Provence,Bouches du Rhône,PACA',
 'France,Portugal, en:switzerland, en:belgium',
 'France, en:germany',
 'France,Monaco',
 'en:SN',
 'France,Royaume-Uni, en:denmark, Suisse',
 'Belgium,France,Germany,Italy,Netherlands,Portugal,Spain,Switzerland,United Kingdom',
 'France,Germany,Switzerland',
 'French Polynesia',
 'Iran',
 'en:GB, en:france',
 'France, en:switzerland, en:belgium, en:morocco',
 'Allemagne, en:france',
 'Martinique,france',
 'Guadeloupe,Martinique,Guyane, en:france',
 'France,de:Deutschland, US',
 'Royaume-Uni, en:france',
 'en:RE, en:france, Suisse',
 'Nederland, en:france',
 'Thailand',
 'France,Martinique',
 'en:denmark, Suisse',
 'Poland, Suisse',
 'France, en:senegal',
 'France, La Réunion',
 'France,Nouvelle-Calédonie',
 'Francia',
 'La Réunion, en:france',
 'New Caledonia,France',
 'France,Guadeloupe, en:switzerland',
 'Guadeloupe, France',
 'Deutschland, en:denmark',
 'Sint Maarten',
 'France,Suisse,Royaume-Uni',
 'Belgique,Danemark,France,Allemagne',
 'Maroc,France',
 'Danemark,Royaume-Uni, en:france',
 'Frankreich,Spanien,Deutschland, Suisse',
 'Frankrijk, Suisse',
 'Denmark,United Kingdom',
 'Germany, Suisse',
 'Netherlands, en:france',
 'Suède, en:france',
 'france, en:switzerland',
 'France, Guyane',
 'France,Vanuatu',
 'France,Grèce,Espagne, en:belgium',
 'Belgique,France,Espagne',
 'Francia, España',
 'France,guadeloupe',
 'Danemark,France, Suisse',
 'France, en:denmark, Suisse',
 'France,Saint-Pierre-et-Miquelon',
 'Belgium,France,Portugal',
 'Saint-Pierre-et-Miquelon,France',
 'France,Portugal,Belgium',
 'België,Frankrijk',
 'Belgique,France,Pologne,Portugal',
 'France, en:algeria',
 'New Caledonia',
 'Jordan',
 'França,Itália,Portugal,Espanha',
 'French Guiana',
 'France,French Guiana',
 'en:GF, en:france',
 'Frankrijk,Zwitserland',
 'Belgique,France,Luxembourg',
 'France,Cora',
 'Canada,France,Grèce,Pays-Bas,Espagne,Royaume-Uni,États-Unis',
 'Guadeloupe,martinique',
 'Guyane, France',
 'France,Portugal,Spain,United Kingdom',
 'France,Spain,United Kingdom',
 'France,Espagne,Royaume-Uni',
 'en:YT',
 'Belgium,France,Mali,Switzerland,United Kingdom',
 'France,Belgique,Pays-Bas',
 'France,Belgium,Spain',
 'Frankrijk,België',
 'Belgien,Frankreich,Deutschland, en:switzerland',
 'France,Netherlands,Switzerland, en:belgium',
 'France, en:spain',
 'España, Suisse',
 'España,Suiza',
 'Belgique,France,Italie,Luxembourg,Mali,Martinique,Suisse',
 'France,Belgique,Pays-Bas,Allemagne',
 'France,Italia',
 'France,Réunion',
 'Guadeloupe,Martinique',
 'Guadeloupe,Martinique,Guyane',
 'Martinique,Guyane,Guadeloupe',
 'Suisse,France,Belgique',
 'France,Bourgogne-Aube-Nogent sur Seine',
 'Guyane,Guadeloupe,Martinique',
 'en:QA',
 'en:NL, en:france',
 'Guadeloupe,Martinique, en:france',
 'Belgique,France,Allemagne,Italie,Pays-Bas,Espagne,Royaume-Uni',
 'Autriche,France',
 'Belgium,France,Luxembourg,Switzerland',
 'France,China',
 'Belgique,France,Allemagne,Italie,Pays-Bas,Royaume-Uni',
 'France,en:Belgique',
 'en:AD',
 'Danemark,France,Guadeloupe',
 'France, en:denmark',
 'en:FR, en:denmark',
 'France,de:Deutschland, Suisse',
 'Inde',
 'Puyricard,France',
 'France,Puyricard',
 'France,Italy,Spain',
 'Autriche',
 'France,United Arab Emirates',
 'Martinique, en:france',
 'en:WF',
 'Espagne,France,Belgique',
 'Tunisia',
 'Belgium,France,Greece',
 'België, en:france',
 'Guadeloupe, en:france, en:belgium',
 'Mayotte',
 'Algérie,Belgique,Canada,France,Maroc,Suisse',
 'France, en:french-polynesia',
 'Frankrijk,Griekenland,Spanje',
 'France,Espagne, en:french-polynesia',
 'France,Grèce,Pays-Bas',
 'Frankreich,Belgien',
 'France,Espagne,Portugal',
 'France,Espagne,Italie,Portugal',
 'Belgium,France,Netherlands',
 'France, en:morocco',
 'España, en:france, en:belgium',
 'France,Estonia',
 'en:NE',
 'en:FR,France',
 'France,Belgique,Allemagne',
 'France,Russie',
 'Luxembourg,France',
 'La Réunion,France',
 'Belgium,France,Italy,United Kingdom',
 'France,Italy,Netherlands,United Kingdom',
 'en:MF',
 'Suisse,Belgique,France',
 'Iceland',
 'Autriche,Danemark,France,Allemagne,Pays-Bas,Espagne,Suisse',
 'Frankrijk,Nederland',
 'Serbia,Switzerland',
 'Bosnia and Herzegovina,Serbia',
 'en:BA',
 'en:DE, Suisse',
 'Belgien,Frankreich,Deutschland,Rumänien',
 'Dänemark,Frankreich,Deutschland',
 'Belgien,Dänemark,Frankreich,Deutschland',
 'Australia,Czech Republic,France,Germany,Hungary',

In [15]:
countries_fr_count = df['countries'].loc[df['countries'].str.contains('be', na=False)].value_counts()
countries_fr_count

France, en:belgium                                                                                                                                                                                                                                                                                                                          80
France, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                                          23
France, en:belgium, en:switzerland                                                                                                                                                                                                                                                                                                          14
Québec                                                                                                                                                                                                                                                                                                                                      13
Québec, Canada                                                                                                                                                                                                                                                                                                                               9
belgium                                                                                                                                                                                                                                                                                                                                      8
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded                                       8
France, en:belgium, Suisse                                                                                                                                                                                                                                                                                                                   6
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded     6
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded                                 5
Allemagne,belgique                                                                                                                                                                                                                                                                                                                           2
France, en:switzerland, en:belgium, en:united-kingdom                                                                                                                                                                                                                                                                                        2
Suisse,France, en:belgium                                                                                                                                                                                                                                                                                                                    2
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded           2
France,Koweït, en:belgium                                                                                                                                                                                                                                                                                                                    1
Czech Republic,France,Iraq, en:belgium, en:switzerland, en:reunion                                                                                                                                                                                                                                                                           1
France,United Kingdom, en:belgium, Suisse                                                                                                                                                                                                                                                                                                    1
Belgium,France,Hungary,Italy,Quebec                                                                                                                                                                                                                                                                                                          1
Emirats Arabes Unis                                                                                                                                                                                                                                                                                                                          1
United Kingdom, en:france, en:belgium                                                                                                                                                                                                                                                                                                        1
Germany, en:belgium                                                                                                                                                                                                                                                                                                                          1
belgium, en:france                                                                                                                                                                                                                                                                                                                           1
France, en:switzerland, en:belgium, en:spain                                                                                                                                                                                                                                                                                                 1
France,United Kingdom, en:belgium                                                                                                                                                                                                                                                                                                            1
en:PT, en:france, en:belgium, en:spain                                                                                                                                                                                                                                                                                                       1
Canada, Québec                                                                                                                                                                                                                                                                                                                               1
France, en:switzerland, en:belgium, en:reunion                                                                                                                                                                                                                                                                                               1
Suisse, en:france, en:belgium                                                                                                                                                                                                                                                                                                                1
France,belgique                                                                                                                                                                                                                                                                                                                              1
France, en:belgium, en:switzerland, en:morocco                                                                                                                                                                                                                                                                                               1
Dänemark,Frankreich,Deutschland, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                  1
France, en:switzerland, en:belgium, en:morocco, en:spain                                                                                                                                                                                                                                                                                     1
France, en:switzerland, en:belgium, en:luxembourg                                                                                                                                                                                                                                                                                            1
France, en:belgium, en:switzerland, en:italy                                                                                                                                                                                                                                                                                                 1
Danemark, en:france, en:belgium, en:switzerland                                                                                                                                                                                                                                                                                              1
Italië,en:belgie,en:duitsland,en:frankrijk,Denemarken,Nederland,Zweden,Noorwegen                                                                                                                                                                                                                                                             1
Guadeloupe, en:france, en:belgium                                                                                                                                                                                                                                                                                                            1
en:SE, en:france, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                                 1
France, en:switzerland, en:belgium, en:reunion, en:morocco                                                                                                                                                                                                                                                                                   1
fr:Québec                                                                                                                                                                                                                                                                                                                                    1
Saint Pierre and Miquelon, en:france, en:belgium                                                                                                                                                                                                                                                                                             1
France, en:switzerland, en:brazil, en:canada, en:belgium                                                                                                                                                                                                                                                                                     1
France, en:denmark, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                               1
France, en:belgium, en:switzerland, en:reunion                                                                                                                                                                                                                                                                                               1
en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded                                     1
en:to-be-completed,en:nutrition-facts-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded                                     1
Dánia,Franciaország,Németország,Portugália,Spanyolország,Nagy-Britannia,Magyarország, en:switzerland, en:belgium                                                                                                                                                                                                                             1
Suisse,Royaume-Uni,France, en:denmark, en:belgium                                                                                                                                                                                                                                                                                            1
Suisse,France, en:belgium, en:morocco, en:spain                                                                                                                                                                                                                                                                                              1
France, en:switzerland, en:belgium, en:italy, en:reunion                                                                                                                                                                                                                                                                                     1
France,Suisse, en:belgium                                                                                                                                                                                                                                                                                                                    1
France,Portugal, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                                  1
France, en:switzerland, en:belgium, en:morocco                                                                                                                                                                                                                                                                                               1
France,Grèce,Espagne, en:belgium                                                                                                                                                                                                                                                                                                             1
France,Netherlands,Switzerland, en:belgium                                                                                                                                                                                                                                                                                                   1
France,Bourgogne-Aube-Nogent sur Seine                                                                                                                                                                                                                                                                                                       1
España, en:france, en:belgium                                                                                                                                                                                                                                                                                                                1
France,Saudi Arabia,Germany, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                      1
Algérie,Belgique,Égypte,France,Maroc,Qatar,Suisse,Tunisie,Émirats arabes unis                                                                                                                                                                                                                                                                1

In [16]:
countries_fr_count.head(25)

France, en:belgium                                                                                                                                                                                                                                                                                                                          80
France, en:switzerland, en:belgium                                                                                                                                                                                                                                                                                                          23
France, en:belgium, en:switzerland                                                                                                                                                                                                                                                                                                          14
Québec                                                                                                                                                                                                                                                                                                                                      13
Québec, Canada                                                                                                                                                                                                                                                                                                                               9
belgium                                                                                                                                                                                                                                                                                                                                      8
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded                                       8
France, en:belgium, Suisse                                                                                                                                                                                                                                                                                                                   6
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded     6
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded                                 5
Allemagne,belgique                                                                                                                                                                                                                                                                                                                           2
France, en:switzerland, en:belgium, en:united-kingdom                                                                                                                                                                                                                                                                                        2
Suisse,France, en:belgium                                                                                                                                                                                                                                                                                                                    2
en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:packaging-code-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded           2
France,Koweït, en:belgium                                                                                                                                                                                                                                                                                                                    1
Czech Republic,France,Iraq, en:belgium, en:switzerland, en:reunion                                                                                                                                                                                                                                                                           1
France,United Kingdom, en:belgium, Suisse                                                                                                                                                                                                                                                                                                    1
Belgium,France,Hungary,Italy,Quebec                                                                                                                                                                                                                                                                                                          1
Emirats Arabes Unis                                                                                                                                                                                                                                                                                                                          1
United Kingdom, en:france, en:belgium                                                                                                                                                                                                                                                                                                        1
Germany, en:belgium                                                                                                                                                                                                                                                                                                                          1
belgium, en:france                                                                                                                                                                                                                                                                                                                           1
France, en:switzerland, en:belgium, en:spain                                                                                                                                                                                                                                                                                                 1
France,United Kingdom, en:belgium                                                                                                                                                                                                                                                                                                            1
en:PT, en:france, en:belgium, en:spain                                                                                                                                                                                                                                                                                                       1
Name: countries, dtype: int64

In [ ]:
# df_be = df.loc[df['countries'].isin(top_fr)]

In [22]:
beverages = ['Alcoholic beverages', 'Beverages']

In [24]:
product_count = df.loc[df['pnns_groups_1'].isin(beverages)]
product_count

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,packaging,packaging_tags,brands,brands_tags,categories,categories_tags,categories_fr,origins,origins_tags,manufacturing_places,manufacturing_places_tags,labels,labels_tags,labels_fr,emb_codes,emb_codes_tags,first_packaging_code_geo,cities,cities_tags,purchase_places,stores,countries,countries_tags,countries_fr,ingredients_text,allergens,allergens_fr,traces,traces_tags,traces_fr,serving_size,no_nutriments,additives_n,additives,additives_tags,additives_fr,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_from_palm_oil_tags,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,ingredients_that_may_be_from_palm_oil_tags,nutrition_grade_uk,nutrition_grade_fr,pnns_groups_1,pnns_groups_2,states,states_tags,states_fr,main_category,main_category_fr,image_url,image_small_url,energy_100g,energy-from-fat_100g,fat_100g,saturated-fat_100g,butyric-acid_100g,caproic-acid_100g,caprylic-acid_100g,capric-acid_100g,lauric-acid_100g,myristic-acid_100g,palmitic-acid_100g,stearic-acid_100g,arachidic-acid_100g,behenic-acid_100g,lignoceric-acid_100g,cerotic-acid_100g,montanic-acid_100g,melissic-acid_100g,monounsaturated-fat_100g,polyunsaturated-fat_100g,omega-3-fat_100g,alpha-linolenic-acid_100g,eicosapentaenoic-acid_100g,docosahexaenoic-acid_100g,omega-6-fat_100g,linoleic-acid_100g,arachidonic-acid_100g,gamma-linolenic-acid_100g,dihomo-gamma-linolenic-acid_100g,omega-9-fat_100g,oleic-acid_100g,elaidic-acid_100g,gondoic-acid_100g,mead-acid_100g,erucic-acid_100g,nervonic-acid_100g,trans-fat_100g,cholesterol_100g,carbohydrates_100g,sugars_100g,sucrose_100g,glucose_100g,fructose_100g,lactose_100g,maltose_100g,maltodextrins_100g,starch_100g,polyols_100g,fiber_100g,proteins_100g,casein_100g,serum-proteins_100g,nucleotides_100g,salt_100g,sodium_100g,alcohol_100g,vitamin-a_100g,beta-carotene_100g,vitamin-d_100g,vitamin-e_100g,vitamin-k_100g,vitamin-c_100g,vitamin-b1_100g,vitamin-b2_100g,vitamin-pp_100g,vitamin-b6_100g,vitamin-b9_100g,folates_100g,vitamin-b12_100g,biotin_100g,pantothenic-acid_100g,silica_100g,bicarbonate_100g,potassium_100g,chloride_100g,calcium_100g,phosphorus_100g,iron_100g,magnesium_100g,zinc_100g,copper_100g,manganese_100g,fluoride_100g,selenium_100g,chromium_100g,molybdenum_100g,iodine_100g,caffeine_100g,taurine_100g,ph_100g,fruits-vegetables-nuts_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
188,0000010090206,http://world-fr.openfoodfacts.org/produit/0000010090206/the-de-noel-aromatise-orange-cannelle-alice-delice,sebleouf,1370977431,2013-06-11T19:03:51Z,1445083431,2015-10-17T12:03:51Z,Thé de Noël aromatisé orange-cannelle,NaN,75 g,aluminium,aluminium,Alice Délice,alice-delice,"Aliments et boissons à base de végétaux,Boissons,Aliments d'origine végétale,Boissons chaudes,Infusions,Thés,Thés noirs,Boissons non sucrées,Thés noirs aromatisés,Thés aromatisés","en:plant-based-foods-and-beverages,en:beverages,en:plant-based-foods,en:hot-beverages,en:plant-based-beverages,en:herbal-teas,en:teas,en:black-teas,en:flavored-teas,en:flavored-black-teas,en:non-sugared-beverages","Aliments et boissons à base de végétaux,Boissons,Aliments d'origine végétale,Boissons chaudes,Boissons à base de végétaux,Infusions,Thés,Thés noirs,Thés aromatisés,Thés noirs aromatisés,Boissons non sucrées",NaN,NaN,France,france,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Lyon,France",Alice Délice,France,en:france,France,"Thé noir de Chine, zestes d'oranges 7,5 %, arômes naturels (cannelle 4,7 %, orange 4,7 %, poudre de cannelle 3,9 %).",NaN,NaN,"Œufs,Gluten,Lait,Moutarde,Fruits à coque,Graines de sésame,Soja,Anhydride sulfureux et sulfites","en:eggs,en:gluten,en:milk,en:mustard,en:nuts,en:sesame-seeds,en:soybeans,en:sulphur-dioxide-and-sulphites","Œufs,Gluten,Lait,Moutarde,Fruits à coque,Graines de sésame,Soja,Anhydride sulfureux et sulfites",NaN,NaN,0.0,[ the-noir-de-chine -> fr:the-noir-de-chine ] [ the-noir-de -> fr:the-noir-de ] [ the-noir -> fr:the-noir ] [ the -> fr:the ] [ zestes-d-oranges-7 -> fr:zestes-d-oranges-7 ] [ zestes-d-oranges -> fr:zestes-d-oranges ] [ zestes-d -> fr:zestes-d ] [ zestes -> fr:zestes ] [ 5 -> en:fd-c ] [ aromes-naturels -> fr:aromes-naturels ] [ aromes -> fr:aromes ] [ cannelle-4 -> fr:cannelle-4 ] [ cannelle -> fr:cannelle ] [ 7 -> en:fd-c ] [ orange-4 -> fr:orange-4 ] [ orange -> fr:orange ] [ 7 -> en:fd-c ] [ poudre-de-cannelle-3 -> fr:poudre-de-cannelle-3 ] [ poudre-de-cannelle -> fr:poudre-de-cannelle ] [ poudre-de -> fr:poudre-de ] [ poudre -> fr:poudre ] [ 9 -> en:fd-c ],NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Beverages,Non-sugared beverages,"en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded","en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded","A vérifier,Complet,Informations nutritionnelles complétées,Ingrédients complétés,Date limite complétée,Caractéristiques complétées,Catégories complétées,Marques complétées,Emballage complété,Quantité complétée,Nom du produit complete,Photos validées,Photos envoyées",en:teas,Thés,http://fr.openfoodfacts.org/images/products/000/001/009/0206/front.5.400.jpg,http://fr.openfoodfacts.org/images/products/000/001/009/0206/front.5.200.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,0000040608754,http://world-fr.openfoodfacts.org/produit/0000040608754/pepsi-nouveau-gout,andre,1345024108,2012-08-15T09:48:28Z,1439141731,2015-08-09T17:35:31Z,"Pepsi, Nouveau goût !",Boisson gazeuse rafraîchissante aux extraits naturels de végétaux,15 cl,Canette aluminium,canette-aluminium,Pepsi,pepsi,Sodas au cola,"en:beverages,en:carbonated-drinks,en:sodas,en:colas,en:sugared-beverages","Boissons,Boissons gazeuses,Sodas,Sodas au cola,Boissons sucrées",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avion,NaN,France,en:france,France,"Eau gazéifiée, sucre, colorant caramel E150d, acidifiant : acide phosphorique, arômes (dont : extraits naturels de végétaux, caféine)",NaN,NaN,NaN,NaN,NaN,150ml,NaN,2.0,[ eau-gazeifiee -> fr:eau-gazeifiee ] [ eau -> fr:eau ] [ sucre -> fr:sucre ] [ colorant -> fr:colorant ] [ e150d -> en:e150d -> exists -- ok ] [ acidifiant -> fr:acidifiant ] [ acide-phosphorique -> en:e338 -> exists -- ok ] [ aromes -> fr:aromes ] [ dont -> fr:dont ] [ extraits-naturels-de-vegetaux -> fr:extraits-naturels-de-vegetaux ] [ extraits-naturels-de -> fr:extraits-naturels-de ] [ extraits-naturels -> fr:extraits-naturels ] [ extraits -> fr:extraits ] [ cafeine -> fr:cafeine ],"en:e150d,en:e338","E150d - Caramel au sulfite d'ammonium,E338 - Acide orthophosphorique",0.0,NaN,NaN,0.0,NaN,NaN,NaN,e,Beverages,Sweetened beverages,"en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded","en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded","A vérifier,Complet,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,Caractéristiques complétées,Catégories complétées,Marques complétées,Emballage complété,Quantité complétée,Nom du produit complete,Photos validées,Photos envoyées",en:sodas,Sodas,http://fr.openfoodfacts.org/images/products/000/004/060/8754/front.5.400.jpg,http://fr.openfoodfacts.org/images/products/000/004/060/8754/front.5.200.jpg,177.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4,10.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0254,0.010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2.0,NaN,NaN
240,0000087177756,http://world-fr.openfoodfacts.org/produit/0000087177756/7up,tacite,1433586486,2015-06-06T10:28:06Z,1433589206,2015-06-06T11:13:26Z,7Up,Boisson gazeuse aux extraits naturels de citron et de citron vert,33 cl,Canette,canette,"7Up,Pepsico","7up,pepsico","Sodas au citron,Boissons sucrées","en:plant-based-foods-and-beverages,en:beverages,en:plant-based-beverages,en:carbonated-drinks,en:fruit-based-beverages,en:sodas,en:fruit-sodas,en:lemon-soft-drinks,en:sugared-beverages","Aliments et boissons à base de végétaux,Boissons,Boissons à base de végétaux,Boissons gazeuses,Boissons aux fruits,Sodas,Sodas aux fruits,Sodas au citron,Boissons sucrées",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Courrières,France",Cora Cafétéria,France,en:france,France,"Eau gazéifiée, sucre, acidifiants (acide citrique, acide malique), arômes (extraits naturels de citron et de citron vert), correcteur d'acidité (citrate de sodium)",NaN,NaN,NaN,NaN,NaN,33 cl,NaN,3.0,[ eau-gazeifiee -> fr:eau-gazeifiee ] [ eau -> fr:eau ] [ sucre -> fr:sucre ] [ acidifiants -> fr:acidifiants ] [ acide-citrique -> en:e330 -> exists -- ok ] [ acide-malique -> en:e296 -> exists -- ok ] [ aromes -> fr:aromes ] [ extraits-naturels-de-citron-et-de-citron-vert -> fr:extraits-naturels-de-citron-et-de-citron-vert ] [ extraits-naturels-de-citron-et-de-citron -> fr:extraits-naturels-de-citron-et-de-citron ] [ extraits-naturels-de-citron-et-de -> fr:extraits-naturels-de-citron-et-de ] [ extraits-naturels-de-citron-et -> fr:extraits-naturels-de-citron-et ] [ extraits-naturels-de-citron -> fr:extraits-naturels-de-citron ] [ extraits-naturels-de -> fr:extraits-naturels-de ] [ extraits-naturels -> fr:extraits-naturels ] [ extraits -> fr:extraits ] [ correcteur-d-acidite -> fr:correcteur-d-acidite ] [ correcteur-d -> fr:correcteur-d ] [ correcteur -> fr:correcteur ] [ citrate-de-sodium -> en:e331 -> exists -- ok ] [ extraits-naturels-de-citron -> fr:extraits-naturels-de-citron ] [ extraits-naturels-de -> fr:extraits-naturels-de ] [ extraits-naturels -> fr:extraits-naturels ] [ extraits -> fr:extraits ] [ citron-vert -> fr:citron-vert ] [ citron -> fr:citron ],"en:e330,en:e296,en:e331","E330 - Acide citrique,E296 - Acide malique,E331 - Citrates de sodium",0.0,NaN,NaN,0.0,NaN,NaN,NaN,e,Beverages,Sweetened beverages,"en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded","en:to-be-checked,en:complete,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:photos-uploaded","A vérifier,Complet,Informations nutritionnelles complétées,Ingrédients complétés,Date limite à compléter,Caractéristiques complétées,Catégories complétées,Marques complétées,Emballage complété,Quantité complétée,Nom du produit complete,Photos validées,Photos envoyées",en:fruit-sodas,Sodas aux fruits,http://fr.openfoodfacts.org/images/products/000/008/717/7756/front.5.400.jpg,http://fr.openfoodfacts.org/images/products/000/008/717/7756/front.5.200.jpg,177.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4,10.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.1000,0.039370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,2.0,NaN,NaN
415,0000886100252,http://world-fr.openfoodfacts.org/produit/0000886100252/pepsi,openfoodfacts-contributors,1403952634,2014-06-28T10:50:34Z,1439141726,2015-08-09T17:35:26Z,Pepsi,NaN,33cl,Canette,canette,Pepsi,pepsi,Soda,"en:beverages,en:carbonated-drinks,en:sodas,en:sugared-beverages","Boissons,Boissons gazeuses,Sodas,Boissons sucrées",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beverages,Sweetened beverages,"en:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded","en:to-be-completed,en:nutrition-facts-to-be-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:characteristics-completed,en:categories-completed,en:brands-completed,en:packaging-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded","A compléter,Informations nutritionnelles à compléter,Ingrédients à compléter,Date limite à compléter,Caractéristiques complétées,Catégories complétées,Marques complétées,Emballage complété,Quantité complétée,Nom du produit complete,Photos à valider,Photos envoyées",en:sodas,Sodas,http://fr.openfoodfacts.org/images/products/000/088/610/0252/front.3.400.jpg,http://fr.openfoodfacts.org/images/products/000/088/610/0252/front.3.200.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,00071543,http://world-fr.openfoodfacts.org/produit/00071543/aloe-vera-grape-apple-juice-m-s,kiliweb,1491759163,2017-04-09T17:32:43Z,1492017342,2017-04-12T17:15:42Z,Aloe Vera Grape & Apple Juice,NaN,NaN,NaN,NaN,M&S,m-s,boissons aux fruits,"en:plant-based-foods-and-beverages,en:beverages,en:plant-based-beverages,en:fruit-based-beverages,en:non-sugared-beverages","Aliments et boissons à base de végétaux,Boissons,Boissons à base de végétaux,Boissons aux fruits,Boissons non sucrées",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e,Beverages,Non-sugared beverages,"en:to-be-completed, en:nutrition-facts-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-to-be-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded","en:to-be-completed,en:nutrition-facts-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:categories-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-to-be-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded","A compléter,Informations nutritionnelles complétées,Ingrédients à compléter,Date limite à compléter,en:Packaging-code-to-be-completed,Caractéristiques à compléter,Catégories complétées,Marques complétées,Emballage à compléter,Quantité à compléter,Nom du produit complete,Photos à valider,Photos envoyées",en:beverages,Boissons,NaN,NaN,155.0,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.1,NaN,NaN,NaN,0.1000,0.039370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320666,9569185896477,http://world-fr.openfoodfacts.org/produit/9569185896477/jus-multifruits-pressade,openfoodfacts-contributors,1471516973,2016-08-18T10:42:53Z,1471539058,2016-08-18T16:50:58Z,Jus multifruits,NaN,1 L,NaN,NaN,Pressade,pressade,Jus multifruits,"en:plant-based-foods-and-beverages,en:beverages,en:plant-based-beverages,en:fruit-based-beverages,en:juices-and-nectars,en:fruit-juices-and-nectars,en:fruit-juices,en:multifruit-juices,en:non-alcoholic-beverages","Aliments et boissons à base de végétaux,Boissons,Boissons à base de végétaux,Boissons aux fruits,Jus et nectars,Jus et nectars de fruits,Jus de fruits,Jus multifruits,Boissons sans alcool",NaN,NaN,NaN,NaN,FSC,en:fsc,FSC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,France,en:france,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beverages,Fruit juices,"en:to-be-completed, en:nutrition-facts-to-be-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:characteristics-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:photos-uploaded","en:to-be-completed,en:nutrition-facts-to-be-completed,en:ingredients-to-be-completed,en:expiration-date-to-be-completed,en:characteristics-to-be-completed,en:categories-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-to-be-validated,en:photos-uploaded","A compléter,Informations nutritionnelles à compléter,Ingrédients à compléter,Date limite à compléter,Caractéristiques à compléter,Catégories complétées,Marques complétées,Emballage à compléter,Quantité complétée,Nom du produit complete,Photos à valider,Photos envoyées",en:fruit-juices,Jus de fruits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.loc[df['pnns_groups_1'].str.contains('Alcoholic beverages', na=False)]

In [27]:
product_count = df.loc[df['product_name'].str.contains('bière', na=False)]
product_count

                 code  \
29062   0033984004009
177149       20015893
177497       20045166
188988  3033210007511
192512  3080210002732
192534  3080216033013
192550  3080216041254
192556  3080216043814
194794  3119780262458
197442  3175681159969
199878  3222471124161
202355  3229820027005
202391  3229820144160
203376  3244851001459
214291  3261570000136
214297  3261570001546
218015  3266191019024
220571  3272460122364
220582  3272460123125
220876  3273190575062
222723  3286010019998
223066  3288842013175
223532  3292590555368
224751  3324020003757
226551  3340040000446
226747  3347430848541
226788  3347431961331
229731  3380380070266
232520  3428881125600
232737  3434221543263
235254  3485853568513
235404  3492270104026
236348  3514123102918
243731  3564709053974
243842  3565700000486
244498  3585260418002
248290  3629103000327
248670  3660989128590
249467  3700029430013
250296  3700311864670
250307  3700311865349
251736  3760028280019
251779  3760029980543
252574  3760075200312
253363  3760110330301
253577  3760121212139
253734  3760123202763
254441  3760182270116
254936  3760230350029
255265  3770001691206
255282  3770001890357
255284  3770001905044
256803  4001436940652
269277  5000119084200
275380  5201309608071
278324  5410228230441
278354  5410263001297
278363  5410263917529
278786  5410971122192
279576  5412929001221
286012  7600015500023
288538  7610807040395
288559  7610807047783
289308  7610845301694
293634  7613269289890
305864  8108561859401
313976  8712000025649
315128  8714800026413

                                                                                                                                              url  \
29062                                            http://world-fr.openfoodfacts.org/produit/0033984004009/levure-de-biere-avec-vitamine-b12-solgar
177149                                                                       http://world-fr.openfoodfacts.org/produit/20015893/biere-perlembourg
177497                                                                       http://world-fr.openfoodfacts.org/produit/20045166/biere-perlembourg
188988                                       http://world-fr.openfoodfacts.org/produit/3033210007511/plombieres-morceaux-de-fruits-confits-nestle
192512                                                     http://world-fr.openfoodfacts.org/produit/3080210002732/kronenbourg-50-cl-biere-blonde
192534                                                  http://world-fr.openfoodfacts.org/produit/3080216033013/original-biere-blonde-kronenbourg
192550                                     http://world-fr.openfoodfacts.org/produit/3080216041254/1664-sans-alcool-biere-blonde-kronenbourg-1664
192556                                                   http://world-fr.openfoodfacts.org/produit/3080216043814/tourtel-twist-bieres-sans-alcool
194794                                                           http://world-fr.openfoodfacts.org/produit/3119780262458/biere-pression-edelweiss
197442                                                             http://world-fr.openfoodfacts.org/produit/3175681159969/levure-de-biere-gerble
199878                                                                     http://world-fr.openfoodfacts.org/produit/3222471124161/corbieres-2014
202355                                    http://world-fr.openfoodfacts.org/produit/3229820027005/superlevure-100-levure-de-biere-gayelord-hauser
202391                                           http://world-fr.openfoodfacts.org/produit/3229820144160/levure-de-biere-selenium-gayelord-hauser
203376                                                        http://world-fr.openfoodfacts.org/produit/3244851001459/amos-biere-speciale-premium
214291                                              http://world-fr.openfoodfacts.org/produit/3261570000136/la-biere-du-demon-brasseurs-de-gayant
214297                                               http://world-fr.openfoodfacts.org/produit/3261570001546/la-goulade-biere-blonde-a-l-ancienne
218015                                        http://world-fr.openfoodfacts.org/produit/3266191019024/levure-de-biere-en-paillettes-la-vie-claire
220571                                                         http://world-fr.openfoodfacts.org/produit/3272460122364/biere-blonde-pur-malt-jade
220582                                        http://world-fr.openfoodfacts.org/produit/3272460123125/fleur-de-houblon-biere-blonde-ipa-castelain
220876                                                             http://world-fr.openfoodfacts.org/produit/3273190575062/la-biere-des-faucheurs
222723                            http://world-fr.openfoodfacts.org/produit/3286010019998/levure-de-biere-vitalite-beaute-laboratoires-vitarmonyl
223066                                               http://world-fr.openfoodfacts.org/produit/3288842013175/corbieres-2011-reserve-des-vignerons
223532                      http://world-fr.openfoodfacts.org/produit/3292590555368/plombieres-avec-des-cubes-de-fruits-confits-au-kirsch-thiriet
224751                                                           http://world-fr.openfoodfacts.org/produit/3324020003757/3-monts-biere-de-flandre
226551                              http://world-fr.openfoodfacts.org/produit/3340040000446/le-pave-de-l-helpe-affine-a-la-biere-de-jenlain-26-mg
226747                                                 http://world-fr.openfoodfacts.org/produit/3347430848541/biere-blonde-bio-moulin-des-moines
226788                                                  http://world-fr.openfoodfacts.org/produit/3347431961331/levure-de-biere-maltee-naturaline
229731                                                            http://world-fr.openfoodfacts.org/produit/3380380070266/levure-de-biere-primeal
232520                                                         http://world-fr.openfoodfacts.org/produit/3428881125600/levure-de-biere-super-diet
232737                                                        http://world-fr.openfoodfacts.org/produit/3434221543263/poulet-a-la-biere-kalifrais
235254                                                                http://world-fr.openfoodfacts.org/produit/3485853568513/corbieres-rose-2015
235404                                             http://world-fr.openfoodfacts.org/produit/3492270104026/levure-de-biere-et-carotte-phytoceutic
236348                           http://world-fr.openfoodfacts.org/produit/3514123102918/domaine-de-villemajou-corbieres-boutenac-gerard-bertrand
243731                 http://world-fr.openfoodfacts.org/produit/3564709053974/coq-au-vin-des-corbieres-et-ses-torsades-nos-regions-ont-du-talent
243842        http://world-fr.openfoodfacts.org/produit/3565700000486/pot-je-vless-a-la-biere-conserverie-saint-christophe-fabrication-artisanale
244498                                      http://world-fr.openfoodfacts.org/produit/3585260418002/terrine-a-la-biere-3-monts-les-toques-du-nord
248290                                                       http://world-fr.openfoodfacts.org/produit/3629103000327/l-biere-d-mincoin-ets-noreni
248670                                                       http://world-fr.openfoodfacts.org/produit/3660989128590/corbieres-2009-les-garrigues
249467                                                        http://world-fr.openfoodfacts.org/produit/3700029430013/flag-speciale-biere-de-luxe
250296                                                              http://world-fr.openfoodfacts.org/produit/3700311864670/dagsbier-biere-blonde
250307                                                             http://world-fr.openfoodfacts.org/produit/3700311865349/biere-forte-7-dagsbier
251736                                                http://world-fr.openfoodfacts.org/produit/3760028280019/biere-blonde-de-bourgogne-temeraire
251779                                                                      http://world-fr.openfoodfacts.org/produit/3760029980543/biere-ninkasi
252574                   http://world-fr.openfoodfacts.org/produit/3760075200312/t-chiot-biloute-affine-a-la-biere-29-m-g-ferme-du-pont-des-loups
253363                                       http://world-fr.openfoodfacts.org/produit/3760110330301/terrine-de-faisan-a-la-biere-ambree-chambord
253577                                                            http://world-fr.openfoodfacts.org/produit/3760121212139/levure-de-biere-biocoop
253734                                             http://world-fr.openfoodfacts.org/produit/3760123202763/la-morgat-la-biere-de-belle-ile-en-mer
254441                                             http://world-fr.openfoodfacts.org/produit/3760182270116/biere-ambree-parisis-brasserie-parisis
254936                        http://world-fr.openfoodfacts.org/produit/3760230350029/chateau-de-l-allemagne-cuvee-andrews-corbieres-aoc-winestar
255265  http://world-fr.openfoodfacts.org/produit/3770001691206/le-fruite-du-cap-gris-nez-brosse-a-la-biere-des-2-caps-22-5-mg-les-freres-bernard
255282                                                          http://world-fr.openfoodfacts.org/produit/3770001890357/terre-de-bieres-caladoise
255284                                                                   http://world-fr.openfoodfacts.org/produit/3770001905044/biere-bio-ambree
256803                                                                    http://world-fr.openfoodfacts.org/produit/4001436940652/biere-valentins
269277                                                                          http://world-fr.openfoodfacts.org/produit/5000119084200/corbieres
275380                                                                       http://world-fr.openfoodfacts.org/produit/5201309608071/mythos-biere
278324                       http://world-fr.openfoodfacts.org/produit/5410228230441/ruby-biere-belge-saveurs-authentiques-et-fruits-rouges-leffe
278354                                                                         http://world-fr.openfoodfacts.org/produit/5410263001297/biere-maes
278363                                                              http://world-fr.openfoodfacts.org/produit/5410263917529/canette-de-biere-maes
278786                                                      http://world-fr.openfoodfacts.org/produit/5410971122192/tongerlo-biere-belge-d-abbaye
279576                                                                  http://world-fr.openfoodfacts.org/produit/5412929001221/chimay-a-la-biere
286012                                                       http://world-fr.openfoodfacts.org/produit/7600015500023/biere-de-pays-ambree-karland
288538                                                        http://world-fr.openfoodfacts.org/produit/7610807040395/gris-de-gris-corbieres-2015
288559                                          http://world-fr.openfoodfacts.org/produit/7610807047783/chateau-etang-des-colombes-corbieres-2014
289308                                                   http://world-fr.openfoodfacts.org/produit/7610845301694/chateau-pech-latt-corbieres-2015
293634                       http://world-fr.openfoodfacts.org/produit/7613269289890/levure-de-biere-vitaminee-vitamine-b1-acide-folique-actilife
305864                                                                              http://world-fr.openfoodfacts.org/produit/8108561859401/biere
313976                                                                 http://world-fr.openfoodfacts.org/produit/8712000025649/fut-biere-heineken
315128                                                      http://world-fr.openfoodfacts.org/produit/8714800026413/bavaria-0-0-alc-biere-blanche

                           creator   created_t      created_datetime  \
29062   openfoodfacts-contributors  1461063405  2016-04-19T10:56:45Z
177149                  agamitsudo  1432214758  2015-05-21T13:25:58Z
177497  openfoodfacts-contributors  1421419348  2015-01-16T14:42:28Z
188988  openfoodfacts-contributors  1486134476  2017-02-03T15:07:56Z
192512              elodiesebbaski  1340391857  2012-06-22T19:04:17Z
192534                    loverock  1484679647  2017-01-17T19:00:47Z
192550                    laminche  1474615329  2016-09-23T07:22:09Z
192556  openfoodfacts-contributors  1480620796  2016-12-01T19:33:16Z
194794                  agamitsudo  1466278309  2016-06-18T19:31:49Z
197442                    sebleouf  1426518982  2015-03-16T15:16:22Z
199878                     kalepom  1454693491  2016-02-05T17:31:31Z
202355  openfoodfacts-contributors  1360958186  2013-02-15T19:56:26Z
202391  openfoodfacts-contributors  1422736556  2015-01-31T20:35:56Z
203376                    jeanbono  1383317881  2013-11-01T14:58:01Z
214291                        kyzh  1435083515  2015-06-23T18:18:35Z
214297  openfoodfacts-contributors  1477872878  2016-10-31T00:14:38Z
218015                      remilk  1414168885  2014-10-24T16:41:25Z
220571  openfoodfacts-contributors  1459515059  2016-04-01T12:50:59Z
220582                    sebleouf  1471023883  2016-08-12T17:44:43Z
220876                  agamitsudo  1484589851  2017-01-16T18:04:11Z
222723                    sebleouf  1436888365  2015-07-14T15:39:25Z
223066                      tacite  1450629563  2015-12-20T16:39:23Z
223532                  agamitsudo  1456076181  2016-02-21T17:36:21Z
224751                     tacinte  1427742885  2015-03-30T19:14:45Z
226551                      tacite  1450378663  2015-12-17T18:57:43Z
226747                       jibec  1455383179  2016-02-13T17:06:19Z
226788  openfoodfacts-contributors  1489950226  2017-03-19T19:03:46Z
229731                      remilk  1415212815  2014-11-05T18:40:15Z
232520                    basileus  1422569095  2015-01-29T22:04:55Z
232737                      tacite  1422369326  2015-01-27T14:35:26Z
235254                 alexcorioze  1465907677  2016-06-14T12:34:37Z
235404  openfoodfacts-contributors  1460918631  2016-04-17T18:43:51Z
236348  openfoodfacts-contributors  1472893168  2016-09-03T08:59:28Z
243731  openfoodfacts-contributors  1434386968  2015-06-15T16:49:28Z
243842  openfoodfacts-contributors  1475405704  2016-10-02T10:55:04Z
244498                      tacite  1454701462  2016-02-05T19:44:22Z
248290                    stephane  1384606874  2013-11-16T13:01:14Z
248670                    sebleouf  1381935391  2013-10-16T14:56:31Z
249467                    malikele  1433858125  2015-06-09T13:55:25Z
250296  openfoodfacts-contributors  1436637015  2015-07-11T17:50:15Z
250307  openfoodfacts-contributors  1461070574  2016-04-19T12:56:14Z
251736                  agamitsudo  1457099105  2016-03-04T13:45:05Z
251779                  agamitsudo  1466196480  2016-06-17T20:48:00Z
252574                      tacite  1427133147  2015-03-23T17:52:27Z
253363                    stephane  1429988286  2015-04-25T18:58:06Z
253577  openfoodfacts-contributors  1491422063  2017-04-05T19:54:23Z
253734                     phoenix  1442147673  2015-09-13T12:34:33Z
254441                     ardoise  1350932550  2012-10-22T19:02:30Z
254936                    stephane  1425648659  2015-03-06T13:30:59Z
255265                      tacite  1454784460  2016-02-06T18:47:40Z
255282                     otourly  1469810908  2016-07-29T16:48:28Z
255284                       jibec  1426964015  2015-03-21T18:53:35Z
256803  openfoodfacts-contributors  1428607413  2015-04-09T19:23:33Z
269277                    bcatelin  1399068177  2014-05-02T22:02:57Z
275380                       cdmad  1391020052  2014-01-29T18:27:32Z
278324                     kiliweb  1490284373  2017-03-23T15:52:53Z
278354  openfoodfacts-contributors  1460139293  2016-04-08T18:14:53Z
278363  openfoodfacts-contributors  1477144358  2016-10-22T13:52:38Z
278786                    pierredh  1466953375  2016-06-26T15:02:55Z
279576                      adline  1369000266  2013-05-19T21:51:06Z
286012                  agamitsudo  1457778149  2016-03-12T10:22:29Z
288538          openfood-ch-import  1486503085  2017-02-07T21:31:25Z
288559          openfood-ch-import  1486502950  2017-02-07T21:29:10Z
289308          openfood-ch-import  1486503746  2017-02-07T21:42:26Z
293634          openfood-ch-import  1486505070  2017-02-07T22:04:30Z
305864                  agamitsudo  1466803931  2016-06-24T21:32:11Z
313976             date-limite-app  1486495694  2017-02-07T19:28:14Z
315128  openfoodfacts-contributors  1462012598  2016-04-30T10:36:38Z

       last_modified_t last_modified_datetime  \
29062       1461079056   2016-04-19T15:17:36Z
177149      1484678035   2017-01-17T18:33:55Z
177497      1490274372   2017-03-23T13:06:12Z
188988      1486137061   2017-02-03T15:51:01Z
192512      1487256704   2017-02-16T14:51:44Z
192534      1484680291   2017-01-17T19:11:31Z
192550      1474615662   2016-09-23T07:27:42Z
192556      1492690396   2017-04-20T12:13:16Z
194794      1467270994   2016-06-30T07:16:34Z
197442      1426532800   2015-03-16T19:06:40Z
199878      1454881398   2016-02-07T21:43:18Z
202355      1490524962   2017-03-26T10:42:42Z
202391      1431091813   2015-05-08T13:30:13Z
203376      1383399178   2013-11-02T13:32:58Z
214291      1477904888   2016-10-31T09:08:08Z
214297      1477876683   2016-10-31T01:18:03Z
218015      1414170633   2014-10-24T17:10:33Z
220571      1459515129   2016-04-01T12:52:09Z
220582      1471024351   2016-08-12T17:52:31Z
220876      1484589890   2017-01-16T18:04:50Z
222723      1436901452   2015-07-14T19:17:32Z
223066      1450629777   2015-12-20T16:42:57Z
223532      1456078045   2016-02-21T18:07:25Z
224751      1458485008   2016-03-20T14:43:28Z
226551      1450623529   2015-12-20T14:58:49Z
226747      1462699189   2016-05-08T09:19:49Z
226788      1489950250   2017-03-19T19:04:10Z
229731      1456948357   2016-03-02T19:52:37Z
232520      1424783315   2015-02-24T13:08:35Z
232737      1427746668   2015-03-30T20:17:48Z
235254      1469050472   2016-07-20T21:34:32Z
235404      1460923123   2016-04-17T19:58:43Z
236348      1472893263   2016-09-03T09:01:03Z
243731      1490363494   2017-03-24T13:51:34Z
243842      1475405770   2016-10-02T10:56:10Z
244498      1454744227   2016-02-06T07:37:07Z
248290      1440240317   2015-08-22T10:45:17Z
248670      1382374364   2013-10-21T16:52:44Z
249467      1433858754   2015-06-09T14:05:54Z
250296      1444572837   2015-10-11T14:13:57Z
250307      1461070627   2016-04-19T12:57:07Z
251736      1457099240   2016-03-04T13:47:20Z
251779      1467271051   2016-06-30T07:17:31Z
252574      1452374381   2016-01-09T21:19:41Z
253363      1430827392   2015-05-05T12:03:12Z
253577      1491422131   2017-04-05T19:55:31Z
253734      1448730854   2015-11-28T17:14:14Z
254441      1358667504   2013-01-20T07:38:24Z
254936      1465721927   2016-06-12T08:58:47Z
255265      1488562347   2017-03-03T17:32:27Z
255282      1469810914   2016-07-29T16:48:34Z
255284      1490282737   2017-03-23T15:25:37Z
256803      1462699192   2016-05-08T09:19:52Z
269277      1417278921   2014-11-29T16:35:21Z
275380      1472294844   2016-08-27T10:47:24Z
278324      1490284448   2017-03-23T15:54:08Z
278354      1460139389   2016-04-08T18:16:29Z
278363      1477144389   2016-10-22T13:53:09Z
278786      1466957068   2016-06-26T16:04:28Z
279576      1369053140   2013-05-20T12:32:20Z
286012      1462699194   2016-05-08T09:19:54Z
288538      1486503085   2017-02-07T21:31:25Z
288559      1486502951   2017-02-07T21:29:11Z
289308      1486503747   2017-02-07T21:42:27Z
293634      1488108348   2017-02-26T11:25:48Z
305864      1469257387   2016-07-23T07:03:07Z
313976      1491985808   2017-04-12T08:30:08Z
315128      1462012858   2016-04-30T10:40:58Z

                                                             product_name  \
29062                                   Levure de bière avec vitamine B12
177149                                                  bière Perlembourg
177497                                                  bière Perlembourg
188988                              plombières Morceaux de fruits confits
192512                                     Kronenbourg 50 cl bière blonde

In [ ]:
product_count

In [28]:
countries_count = product_count['countries'].value_counts()
countries_count

France                                                         44
en:FR                                                          13
Suisse                                                          4
en:BE                                                           2
France, Suisse                                                  1
Canada,France,Grèce,Pays-Bas,Espagne,Royaume-Uni,États-Unis     1
Côte d'Ivoire                                                   1
United Kingdom                                                  1
Italia                                                          1
Name: countries, dtype: int64

In [29]:
### minima 4-5k éléments.

df['countries'].value_counts()

US                                            169928
France                                         77292
en:FR                                          16979
Suisse                                         12314
Deutschland                                     6161
                                               ...
Tschechien,Dänemark,Frankreich,Deutschland         1
Danemark,Allemagne,France                          1
Dänemark,Frankreich,Deutschland,Indien             1
Dänemark                                           1
Hong Kong,China                                    1
Name: countries, Length: 1434, dtype: int64

In [30]:
df.shape

(320772, 162)

In [ ]:
## uniquement france : déjà fait
## check contributeur : virer les moins complets

In [ ]:
## check éq .info() group by sous catégories (pays, pnn_groups...) pour trouver cats les plus "propre"
## opérer grande maille => petite maille

In [ ]:
# exemple : catégoriser pour différents régimes les aliments (diabète, sportif, etc..)

In [ ]:
# favoriser méthodes au lieu d'anova : whitney