# Imports

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import utils.UVA as UVA
import utils.MVA as MVA
import utils.PCA as PCA

from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, PowerTransformer
from sklearn.decomposition import PCA as skPCA
from sklearn.compose import ColumnTransformer

from sklearn.cluster import KMeans, DBSCAN, MiniBatchKMeans, AgglomerativeClustering
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score, silhouette_samples

from sklearn.metrics.cluster import adjusted_rand_score

In [77]:
# import dataframes. Names = df + max date of orders
df_2018_10 = pd.read_csv('data/customers_2016-09-04_2018-10-17.csv')
df_2018_08 = pd.read_csv('data/customers_2016-09-04_2018-08-17.csv')
df_2018_06 = pd.read_csv('data/customers_2016-09-04_2018-06-17.csv')
df_2018_04 = pd.read_csv('data/customers_2016-09-04_2018-04-17.csv')
df_2018_02 = pd.read_csv('data/customers_2016-09-04_2018-02-17.csv')
df_2017_12 = pd.read_csv('data/customers_2016-09-04_2017-12-17.csv')
df_2017_10 = pd.read_csv('data/customers_2016-09-04_2017-10-17.csv')

In [78]:
print(df_2018_10.shape)
print(df_2018_08.shape)
print(df_2018_06.shape)
print(df_2018_04.shape)
print(df_2018_02.shape)
print(df_2017_12.shape)
print(df_2017_10.shape)

(94700, 15)
(93127, 15)
(79835, 15)
(67011, 15)
(53663, 15)
(41324, 15)
(28621, 15)

# Select the same unique points / customer_unique_id

In [ ]:
# Use customer_unique_id from the older dataset as the basis / filter for the future datasets

In [95]:
def transform_df(transform_df, base_df, col):
    transform_df = transform_df[transform_df[col].isin(base_df[col])].sort_values(by=col).set_index(col)
    #transform_df = transform_df[transform_df[col].isin(base_df[col])].sort_values(by=col).set_index(col).reset_index(drop=True)
    
    return transform_df

In [98]:
df_2018_10 = transform_df(df_2018_10, df_2017_10, 'customer_unique_id')
df_2018_08 = transform_df(df_2018_08, df_2017_10, 'customer_unique_id')
df_2018_06 = transform_df(df_2018_06, df_2017_10, 'customer_unique_id')
df_2018_04 = transform_df(df_2018_04, df_2017_10, 'customer_unique_id')
df_2018_02 = transform_df(df_2018_02, df_2017_10, 'customer_unique_id')
df_2017_12 = transform_df(df_2017_12, df_2017_10, 'customer_unique_id')
df_2017_10 = transform_df(df_2017_10, df_2017_10, 'customer_unique_id')

In [99]:
print(df_2018_10.shape)
print(df_2018_08.shape)
print(df_2018_06.shape)
print(df_2018_04.shape)
print(df_2018_02.shape)
print(df_2017_12.shape)
print(df_2017_10.shape)

(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)

In [100]:
df_2017_10.head()

,recency,baby,computers,fixed_telephony,furniture_decor,musical_instruments,sports_leisure,telephony,toys,other_categories,freight_value,frequency_medium,mean_review_score,ratio_comment_message
customer_unique_id,,,,,,,,,,,,,,
0000f46a3911fa3c0805444483337064,221,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,69.0,17.22,0,4,0.0
0000f6ccb0745a6a4b88665a16c9f078,5,0.0,0.0,0.0,0.0,0.0,0.0,25.99,0.0,0.0,17.63,0,5,100.0
0005e1862207bf6ccc02e4228effd9a0,227,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,135.0,15.12,0,4,0.0
0006fdc98a402fceb4eb0ee528f6a8d4,91,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,15.10,0,1,100.0
000a5ad9c4601d2bbdd9ed765d5213b3,67,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,14.29,1,4,0.0

# train kmeans_8 all datasets

In [103]:
def customTransform(df):
    # sélection colonnes avec skewness élevée :
    skewness = df.select_dtypes(include=np.number).skew()
    treshold_skew = 1.0
    cols_skewed = skewness[skewness > treshold_skew].index.tolist()
    cols_unskewed = skewness[skewness < treshold_skew].index.tolist()

    print("Colonnes numériques avec une skewness supérieure à la limite :")
    print(cols_skewed)
    print(cols_unskewed)
    
    # Création du ColumnTransformer
    transformer = ColumnTransformer([
        #('minmax', MinMaxScaler(), cols_skewed),
        ('power', PowerTransformer(), cols_skewed),
        ('standard', StandardScaler(), cols_unskewed)
    ])
    
    X_std = pd.DataFrame(transformer.fit_transform(df), columns=df.columns)
    return X_std

In [105]:
X_2018_10 = customTransform(df_2018_10)
X_2018_08 = customTransform(df_2018_08)
X_2018_06 = customTransform(df_2018_06)
X_2018_04 = customTransform(df_2018_04)
X_2018_02 = customTransform(df_2018_02)
X_2017_12 = customTransform(df_2017_12)
X_2017_10 = customTransform(df_2017_10)

Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value', 'frequency_medium']
['recency', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value', 'frequency_medium']
['recency', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value', 'frequency_medium']
['recency', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value', 'frequency_medium']
['recency', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value']
['recency', 'frequency_medium', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value']
['recency', 'frequency_medium', 'mean_review_score', 'ratio_comment_message']
Colonnes numériques avec une skewness supérieure à la limite :
['baby', 'computers', 'fixed_telephony', 'furniture_decor', 'musical_instruments', 'sports_leisure', 'telephony', 'toys', 'other_categories', 'freight_value']
['recency', 'frequency_medium', 'mean_review_score', 'ratio_comment_message']

In [106]:
print(X_2018_10.shape)
print(X_2018_08.shape)
print(X_2018_06.shape)
print(X_2018_04.shape)
print(X_2018_02.shape)
print(X_2017_12.shape)
print(X_2017_10.shape)

(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)
(28621, 14)

In [107]:
X_2018_10.head()

,recency,baby,computers,fixed_telephony,furniture_decor,musical_instruments,sports_leisure,telephony,toys,other_categories,freight_value,frequency_medium,mean_review_score,ratio_comment_message
0,-0.172817,-0.054577,-0.064068,-0.289837,-0.07403,-0.30453,-0.220932,-0.234928,1.847746,-0.140194,-0.684935,1.234801,0.704966,-0.863793
1,-0.172817,-0.054577,-0.064068,-0.289837,-0.07403,-0.30453,4.526283,-0.234928,-0.543709,-0.092037,-0.684935,-1.214155,0.704966,1.170283
2,-0.172817,-0.054577,-0.064068,-0.289837,-0.07403,-0.30453,-0.220932,-0.234928,1.871149,-0.413774,-0.684935,1.302828,0.704966,-0.863793
3,-0.172817,-0.054577,-0.064068,-0.289837,-0.07403,-0.30453,-0.220932,-0.234928,-0.543709,-0.416624,-0.684935,-0.239108,0.704966,1.170283
4,-0.172817,-0.054577,-0.064068,-0.289837,-0.07403,-0.30453,-0.220932,-0.234928,-0.543709,-0.536485,1.455248,-0.511214,-0.014453,-0.863793

In [108]:
kmeans_8_X_2018_10 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2018_10)
kmeans_8_X_2018_08 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2018_08)
kmeans_8_X_2018_06 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2018_06)
kmeans_8_X_2018_04 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2018_04)
kmeans_8_X_2018_02 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2018_02)
kmeans_8_X_2017_12 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2017_12)
kmeans_8_X_2017_10 = KMeans(n_clusters=8, verbose=1, random_state=0).fit(X_2017_10)

Initialization complete
Iteration 0, inertia 274612.9238011333.
Iteration 1, inertia 210117.52235608926.
Iteration 2, inertia 206249.96794172042.
Iteration 3, inertia 204042.3880502939.
Iteration 4, inertia 204019.01334120307.
Iteration 5, inertia 204017.38890518525.
Converged at iteration 5: center shift 1.9497034298066814e-05 within tolerance 9.999999999999561e-05.
Initialization complete
Iteration 0, inertia 278618.57782481.
Iteration 1, inertia 202708.5286695574.
Iteration 2, inertia 202694.0297382821.
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 306873.9073390304.
Iteration 1, inertia 227429.53391114573.
Iteration 2, inertia 225766.6990362496.
Iteration 3, inertia 223650.66254711576.
Iteration 4, inertia 222309.22199300898.
Iteration 5, inertia 221580.01934126025.
Iteration 6, inertia 220877.1274107091.
Iteration 7, inertia 220029.85281800688.
Iteration 8, inertia 219376.3989288951.
Iteration 9, inertia 219169.1963208156.
Iteration 10, inertia 219100.06125973462.
Iteration 11, inertia 218984.9721667009.
Iteration 12, inertia 218495.5297939215.
Iteration 13, inertia 217808.44646418138.
Iteration 14, inertia 217718.33941391722.
Iteration 15, inertia 217691.56098239415.
Iteration 16, inertia 217690.913335689.
Converged at iteration 16: strict convergence.
Initialization complete
Iteration 0, inertia 290499.5364010664.
Iteration 1, inertia 222473.67898303908.
Iteration 2, inertia 218766.5987763945.
Iteration 3, inertia 215733.49574940262.
Iteration 4, inertia 214596.33355839227.
Iteration 5, inertia 212166.27642879146.
Iteration 6, inertia 210731.27536707837.
Iteration 7, inertia 210722.53375484588.
Converged at iteration 7: center shift 1.101661450419925e-05 within tolerance 0.00010000000000000522.
Initialization complete
Iteration 0, inertia 285337.39559688745.
Iteration 1, inertia 239146.4856062696.
Iteration 2, inertia 235577.20532901367.
Iteration 3, inertia 233663.32756631495.
Iteration 4, inertia 232906.9216991149.
Iteration 5, inertia 232467.91404636172.
Iteration 6, inertia 231885.9250646625.
Iteration 7, inertia 230438.95954481928.
Iteration 8, inertia 225163.82715663637.
Iteration 9, inertia 215983.41732710137.
Iteration 10, inertia 215741.6534608526.
Iteration 11, inertia 215740.05749491192.
Converged at iteration 11: center shift 1.6227053772528678e-06 within tolerance 0.00010000000000001864.
Initialization complete
Iteration 0, inertia 315074.3077588681.
Iteration 1, inertia 271760.6155486107.
Iteration 2, inertia 268591.2117766014.
Iteration 3, inertia 265589.8022331291.
Iteration 4, inertia 257449.62984736136.
Iteration 5, inertia 247686.95828741635.
Iteration 6, inertia 245427.40188984064.
Iteration 7, inertia 245416.72317736334.
Converged at iteration 7: center shift 4.6882408776374454e-05 within tolerance 0.00010000000000000877.
Initialization complete
Iteration 0, inertia 269571.6125814804.
Iteration 1, inertia 215747.15819009065.
Iteration 2, inertia 214255.45540515505.
Iteration 3, inertia 213521.82422346433.
Iteration 4, inertia 211162.1547544049.
Iteration 5, inertia 208475.05074059695.
Iteration 6, inertia 208023.98744976698.
Iteration 7, inertia 208022.99233097833.
Converged at iteration 7: strict convergence.

In [113]:
# apply labels to first df

X_labels = X_2017_10.copy()
X_labels['km_2018_10'] = kmeans_8_X_2018_10.labels_
X_labels['km_2018_08'] = kmeans_8_X_2018_08.labels_
X_labels['km_2018_06'] = kmeans_8_X_2018_06.labels_
X_labels['km_2018_04'] = kmeans_8_X_2018_04.labels_
X_labels['km_2018_02'] = kmeans_8_X_2018_02.labels_
X_labels['km_2017_12'] = kmeans_8_X_2017_12.labels_
X_labels['km_2017_10'] = kmeans_8_X_2017_10.labels_

In [114]:
X_labels

,recency,baby,computers,fixed_telephony,furniture_decor,musical_instruments,sports_leisure,telephony,toys,other_categories,...,frequency_medium,mean_review_score,ratio_comment_message,km_2018_10,km_2018_08,km_2018_06,km_2018_04,km_2018_02,km_2017_12,km_2017_10
0,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,1.869734,-0.111998,...,-0.669877,-0.090125,-0.860951,3,1,1,1,4,1,2
1,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,4.549617,-0.233766,-0.537311,-0.063104,...,-0.669877,0.672583,1.167715,0,0,0,0,0,0,0
2,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,1.891437,-0.389753,...,-0.669877,-0.090125,-0.860951,3,1,2,1,4,1,2
3,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,-0.537311,-0.392645,...,-0.669877,-2.378249,1.167715,1,1,3,3,6,4,1
4,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,-0.537311,-0.514331,...,1.425484,-0.090125,-0.860951,3,3,2,2,3,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28616,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,1.877899,-0.038656,...,-0.669877,-0.090125,-0.860951,3,1,2,1,4,1,2
28617,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,1.839188,-0.392645,...,-0.669877,-0.090125,1.167715,1,1,3,3,6,2,2
28618,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,-0.537311,3.745472,...,-0.669877,-2.378249,-0.860951,3,1,2,1,4,6,1
28619,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,-0.537311,0.424710,...,1.425484,-0.852833,-0.860951,3,3,1,2,3,6,6
28620,-0.17185,-0.05393,-0.063792,-0.286994,-0.073311,-0.302057,-0.219799,-0.233766,1.860721,-0.471239,...,-0.669877,0.672583,-0.860951,3,1,1,1,4,1,2

# Compute ARI