In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

/home/mijka/.pyenv/versions/3.9.7/envs/oclass4/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [16]:
df = pd.read_csv('data/olist_rfm.csv')

In [17]:
df.head()

                 customer_unique_id  recency  frequency  monetary
0  7c396fd4830fd04220f754e42b4e5bff      380          2     65.38
1  af07308b275d755c9edb36a90c618231       85          1    118.70
2  3a653a41f6f9fc3d2a113cf8398680e8       70          1    159.90
3  7c142cf63193a1473d2e66489a9ae977      333          1     45.00
4  72632f0f9dd73dfee390c9b22eb56dd6      246          1     19.90

In [ ]:
# remove customer_unique_id

In [5]:
df.shape

(96096, 5)

In [8]:
df.dtypes

Unnamed: 0              int64
customer_unique_id     object
recency                 int64
frequency               int64
monetary              float64
dtype: object

In [13]:
df.isna().sum()

Unnamed: 0            0
customer_unique_id    0
recency               0
frequency             0
monetary              0
dtype: int64

In [14]:
quantiles = df.quantile(q=[0.25,0.5,0.75])
quantiles

      Unnamed: 0  recency  frequency  monetary
0.25    24023.75    164.0        1.0     45.99
0.50    48047.50    269.0        1.0     89.00
0.75    72071.25    397.0        1.0    154.00

### PCA

In [6]:
# K-Means

In [7]:
# DBscan