# Imports

## libraries

%load_ext autoreload
%autoreload 2

In [2]:
import os

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# https://numpy.org/doc/stable/release/2.0.0-notes.html#representation-of-numpy-scalars-changed
np.set_printoptions(legacy='1.21')

## data

In [4]:
csv_path = '../data/'
file_names = [x for x in os.listdir(csv_path) if ".csv" in x]
file_names

['application_train.csv',
 'HomeCredit_columns_description.csv',
 'POS_CASH_balance.csv',
 'previous_application.csv',
 'bureau_balance.csv',
 'credit_card_balance.csv',
 'installments_payments.csv',
 'sample_submission.csv',
 'bureau.csv',
 'application_test.csv']

In [5]:
len(file_names)

10

In [23]:
# Créer le dictionnaire avec remplacement de "application_" par "X_"
file_dict = {file_name: file_name.replace('.csv', '').replace('application_', 'X_') for file_name in file_names}

# Afficher le dictionnaire
file_dict

{'application_train.csv': 'X_train',
 'HomeCredit_columns_description.csv': 'HomeCredit_columns_description',
 'POS_CASH_balance.csv': 'POS_CASH_balance',
 'previous_application.csv': 'previous_application',
 'bureau_balance.csv': 'bureau_balance',
 'credit_card_balance.csv': 'credit_card_balance',
 'installments_payments.csv': 'installments_payments',
 'sample_submission.csv': 'sample_submission',
 'bureau.csv': 'bureau',
 'application_test.csv': 'X_test'}

In [24]:
for file_name, df_name in file_dict.items():
    try:
        # Charger le fichier CSV dans un DataFrame
        df = pd.read_csv(f'{csv_path + file_name}', encoding='ISO-8859-1')

        # Supprimer la colonne "Unnamed: 0" si elle existe
        if 'Unnamed: 0' in df.columns:
            df.drop(columns=['Unnamed: 0'], inplace=True)

        # Créer une variable globale pour le DataFrame
        globals()[df_name] = df

        print(f"{file_name} chargé avec succès dans {df_name}.")
    except Exception as e:
        print(f"Erreur lors du chargement de {file_name}: {e}")
        
print(f"\n L'ensemble des données dans {csv_path} ont été chargées avec succès.")

application_train.csv chargé avec succès dans X_train.
HomeCredit_columns_description.csv chargé avec succès dans HomeCredit_columns_description.
POS_CASH_balance.csv chargé avec succès dans POS_CASH_balance.
previous_application.csv chargé avec succès dans previous_application.
bureau_balance.csv chargé avec succès dans bureau_balance.
credit_card_balance.csv chargé avec succès dans credit_card_balance.
installments_payments.csv chargé avec succès dans installments_payments.
sample_submission.csv chargé avec succès dans sample_submission.
bureau.csv chargé avec succès dans bureau.
application_test.csv chargé avec succès dans X_test.

In [26]:
X_train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
X_test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

# Explo